-- SPDX-License-Identifier: Apache-2.0
module Main (main) where

import System.Directory (doesDirectoryExist, listDirectory)
import System.Environment (getArgs)
import System.Exit (exitFailure)
import System.FilePath ((</>), takeExtension)
import System.IO (hSetEncoding, stdout, stderr, utf8)
import Control.Monad (forM, unless)
import qualified GHC.IO.Encoding as Enc
import qualified CryptoGen
import qualified CBORGen
import qualified FSMGen
import qualified TestGen

-- | Code generator entry point.
-- Reads all .spec, .fsm, and .schema files from app/codegen/Specs/
-- and writes generated Haskell modules to src/UmbraVox/ and test/Test/.
--
-- Generated by UmbraVox.CodeGen v0.1.0
-- TQL-1 qualified artifact (DO-330)
main :: IO ()
main = do
    -- Ensure UTF-8 encoding regardless of system locale (fixes nix-shell --pure)
    Enc.setLocaleEncoding Enc.utf8
    hSetEncoding stdout utf8
    hSetEncoding stderr utf8
    args <- getArgs
    if "--check" `elem` args
        then runCheck
        else runGenerate

-- | Drift / idempotency check: regenerate every crypto spec's artifacts
-- in-memory and compare them against the committed on-disk files, writing
-- nothing. Exits non-zero if any generated file has drifted (was hand-edited
-- or is stale relative to the generator). This guards against accidental edits
-- to Generated/*.hs and against generator changes that were never regenerated.
runCheck :: IO ()
runCheck = do
    let specsDir = "app/codegen/Specs"
    exists <- doesDirectoryExist specsDir
    unless exists $ do
        putStrLn $ "Error: specs directory not found: " ++ specsDir
        exitFailure
    files <- listDirectory specsDir
    let specFiles = filter (\f -> takeExtension f == ".spec") files
    putStrLn "UmbraVox CryptoGen drift check"
    putStrLn $ "  Spec files: " ++ show (length specFiles)
    putStrLn ""
    reports <- forM specFiles $ \f -> CryptoGen.checkSpec (specsDir </> f)
    let drifts = concat reports
    if null drifts
        then putStrLn "OK: all generated crypto artifacts match the generator (no drift)."
        else do
            putStrLn "DRIFT DETECTED in generated crypto artifacts:"
            mapM_ (\d -> putStrLn ("  " ++ d)) drifts
            putStrLn ""
            putStrLn "Fix: do NOT hand-edit Generated/*.hs or csrc/generated/*.c."
            putStrLn "     Edit app/codegen/CryptoGen.hs (or the .spec), then regenerate."
            exitFailure

runGenerate :: IO ()
runGenerate = do
    let specsDir = "app/codegen/Specs"
    exists <- doesDirectoryExist specsDir
    if not exists
        then putStrLn $ "Error: specs directory not found: " ++ specsDir
        else do
            files <- listDirectory specsDir
            let specFiles   = filter (\f -> takeExtension f == ".spec")   files
                fsmFiles    = filter (\f -> takeExtension f == ".fsm")    files
                schemaFiles = filter (\f -> takeExtension f == ".schema") files

            putStrLn "UmbraVox Code Generator v0.1.0"
            putStrLn $ "  Spec files:   " ++ show (length specFiles)
            putStrLn $ "  FSM files:    " ++ show (length fsmFiles)
            putStrLn $ "  Schema files: " ++ show (length schemaFiles)
            putStrLn ""

            -- Process crypto specs
            mapM_ (\f -> do
                putStrLn $ "Processing: " ++ f
                CryptoGen.processSpec (specsDir </> f)
                TestGen.generateCryptoTests (specsDir </> f)
                ) specFiles

            -- Process FSM specs
            mapM_ (\f -> do
                putStrLn $ "Processing: " ++ f
                FSMGen.processFSM (specsDir </> f)
                TestGen.generateFSMTests (specsDir </> f)
                ) fsmFiles

            -- Process CBOR schemas
            mapM_ (\f -> do
                putStrLn $ "Processing: " ++ f
                CBORGen.processSchema (specsDir </> f)
                TestGen.generateCBORTests (specsDir </> f)
                ) schemaFiles

            putStrLn "Code generation complete."
