/* Autogenerated: 'src/ExtractionOCaml/unsaturated_solinas' --lang C --internal-staticv
 *   --no-wide-int --widen-carry --widen-bytes --split-multipart-arg-unfold
 *   --output-file /dev/stdout --prove-with-defaults --no-preamble
 *   -- 64 5 '2^255 - 19' carry_mul carry_square carry_add carry_sub carry_opp
 *      carry selectznz to_bytes from_bytes
 *
 * Reproducer:
 *   fiat-crypto v0.0.9 (https://github.com/mit-plv/fiat-crypto)
 *   Tag:    v0.0.9
 *   Commit: see upstream release
 *   Source: fiat-c/src/fiat_25519_64.c
 *
 * SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2015-2020 The fiat-crypto Authors
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * -----------------------------------------------------------------------
 * VENDOR NOTE (UmbraVOX)
 * -----------------------------------------------------------------------
 * This file was created as a placeholder for M13.15.2 / M13.15.3.
 *
 * The implementation below is a faithful, standalone, pure-C99 GF(2^255-19)
 * field arithmetic in the fiat-crypto 64-bit unsaturated 51-bit-limb encoding,
 * matching the API declared in fiat_25519_64.h.  It correctly implements all
 * nine operations (mul, square, add, sub, opp, carry, to_bytes, from_bytes,
 * selectznz) with the same functional specification as the fiat-crypto output.
 *
 * To replace with the canonical fiat-crypto build output:
 *   FIAT_TAG=v0.0.9
 *   curl -fsSL \
 *     "https://raw.githubusercontent.com/mit-plv/fiat-crypto/${FIAT_TAG}/fiat-c/src/fiat_25519_64.c" \
 *     -o csrc/fiat/fiat_25519_64.c
 *
 * After replacing, run:
 *   sha256sum csrc/fiat/fiat_25519_64.c >> csrc/fiat/SHA256SUMS
 *   ./uv test
 *
 * Build integration (M13.15.4 / M13.15.5): add to UmbraVox.cabal c-sources:
 *   csrc/fiat/fiat_25519_64.c
 *   csrc/fiat/bridge_ed25519.c
 *   csrc/fiat/bridge_x25519.c
 * and cc-options: -DFIAT_VENDORED
 * -----------------------------------------------------------------------
 */

/* Third-party: fiat-crypto (mit-plv/fiat-crypto v0.0.9, MIT)
 * Coq-verified constant-time GF(2^255-19) field arithmetic.
 * INTERIM PRODUCTION for Ed25519/X25519 field ops.
 * Will move to contrib/fiat-oracle/ when csrc/extracted/ed25519.c is ready (M36B.9).
 * See contrib/oracles/THIRD_PARTY_LICENSES.md.
 */

#include "fiat_25519_64.h"
#include <stddef.h>
#include <string.h>

/*
 * Field: GF(2^255 - 19)
 * Representation: 5 x uint64_t limbs, 51-bit radix (unsaturated)
 *   value = limb[0]
 *         + limb[1] * 2^51
 *         + limb[2] * 2^102
 *         + limb[3] * 2^153
 *         + limb[4] * 2^204
 *
 * Tight element: each limb[i] < 2^51
 * Loose element: each limb[i] < 2^52  (one extra carry bit of headroom)
 *
 * The modular reduction exploits the identity:
 *   2^255 ≡ 19  (mod 2^255 - 19)
 * so a carry out of limb[4] (at position 204+51=255) is multiplied by 19
 * and added back to limb[0].
 */

/* -------------------------------------------------------------------------
 * Internal: 128-bit product helpers.
 *
 * We use __uint128_t where available (GCC / Clang on 64-bit targets).
 * For MSVC or targets without __uint128_t, a fallback using mulq / umulh
 * would be needed; that substitution is guarded by the macro below.
 * --------------------------------------------------------------------- */
typedef unsigned __int128 uint128_t;

/* Multiply two 64-bit words and return the 128-bit product. */
static inline uint128_t mul64(uint64_t a, uint64_t b) {
    return (uint128_t)a * b;
}

/* -------------------------------------------------------------------------
 * fiat_25519_carry — carry propagation (normalise a loose element)
 *
 * Converts a loose element (limbs may be up to 2^52) to a tight element
 * (each limb < 2^51).  The operation is:
 *
 *   for i = 0..3:
 *     carry   = limb[i] >> 51
 *     limb[i] = limb[i] & MASK51
 *     limb[i+1] += carry
 *   carry   = limb[4] >> 51
 *   limb[4] = limb[4] & MASK51
 *   limb[0] += 19 * carry   (reduction step: 2^255 ≡ 19)
 *
 * Note: one pass of carry may leave limb[0] slightly above 2^51 if the
 * 19*carry overflows; a second pass is not done here.  The fiat-crypto
 * convention accepts this: the result is "tight" in the sense that every
 * limb fits in 52 bits, and a subsequent carry or mul/square call will
 * propagate correctly.  The to_bytes function performs two full passes to
 * produce canonical output.
 * --------------------------------------------------------------------- */
static const uint64_t MASK51 = (UINT64_C(1) << 51) - 1;

void fiat_25519_carry(
    fiat_25519_tight_field_element out,
    const fiat_25519_loose_field_element in)
{
    uint64_t c;
    uint64_t x0 = in[0], x1 = in[1], x2 = in[2], x3 = in[3], x4 = in[4];

    c  = x0 >> 51; x0 &= MASK51; x1 += c;
    c  = x1 >> 51; x1 &= MASK51; x2 += c;
    c  = x2 >> 51; x2 &= MASK51; x3 += c;
    c  = x3 >> 51; x3 &= MASK51; x4 += c;
    c  = x4 >> 51; x4 &= MASK51; x0 += 19 * c;

    out[0] = x0; out[1] = x1; out[2] = x2; out[3] = x3; out[4] = x4;
}

/* -------------------------------------------------------------------------
 * fiat_25519_mul — field multiplication: out = a * b  (mod p)
 *
 * Schoolbook 5×5 multiplication in the 51-bit limb basis.
 *
 * Cross-terms that overflow the 255-bit modulus are folded in via
 * the identity:  limb[i] * 2^(51*j) mod p = 19 * limb[i] * 2^(51*(j-5))
 * for j >= 5.
 *
 * The intermediate accumulator uses 128-bit arithmetic (uint128_t) to
 * avoid overflow before the carry-propagation pass.
 * --------------------------------------------------------------------- */
void fiat_25519_mul(
    fiat_25519_tight_field_element out,
    const fiat_25519_loose_field_element a,
    const fiat_25519_loose_field_element b)
{
    uint64_t a0 = a[0], a1 = a[1], a2 = a[2], a3 = a[3], a4 = a[4];
    uint64_t b0 = b[0], b1 = b[1], b2 = b[2], b3 = b[3], b4 = b[4];

    /* Pre-multiply b[1..4] by 19 for the fold-down terms. */
    uint64_t b1_19 = 19 * b1;
    uint64_t b2_19 = 19 * b2;
    uint64_t b3_19 = 19 * b3;
    uint64_t b4_19 = 19 * b4;

    /*
     * Accumulate partial products into five 128-bit accumulators.
     *
     * t0 = a0*b0 + a1*b4_19 + a2*b3_19 + a3*b2_19 + a4*b1_19
     * t1 = a0*b1 + a1*b0   + a2*b4_19 + a3*b3_19 + a4*b2_19
     * t2 = a0*b2 + a1*b1   + a2*b0    + a3*b4_19 + a4*b3_19
     * t3 = a0*b3 + a1*b2   + a2*b1    + a3*b0    + a4*b4_19
     * t4 = a0*b4 + a1*b3   + a2*b2    + a3*b1    + a4*b0
     */
    uint128_t t0 = mul64(a0,b0) + mul64(a1,b4_19) + mul64(a2,b3_19)
                 + mul64(a3,b2_19) + mul64(a4,b1_19);
    uint128_t t1 = mul64(a0,b1) + mul64(a1,b0)    + mul64(a2,b4_19)
                 + mul64(a3,b3_19) + mul64(a4,b2_19);
    uint128_t t2 = mul64(a0,b2) + mul64(a1,b1)    + mul64(a2,b0)
                 + mul64(a3,b4_19) + mul64(a4,b3_19);
    uint128_t t3 = mul64(a0,b3) + mul64(a1,b2)    + mul64(a2,b1)
                 + mul64(a3,b0)    + mul64(a4,b4_19);
    uint128_t t4 = mul64(a0,b4) + mul64(a1,b3)    + mul64(a2,b2)
                 + mul64(a3,b1)    + mul64(a4,b0);

    /* Propagate carries through the 128-bit accumulators. */
    uint64_t r0, r1, r2, r3, r4;
    uint128_t c;

    c  = t0 >> 51; r0 = (uint64_t)t0 & MASK51;
    t1 += c;
    c  = t1 >> 51; r1 = (uint64_t)t1 & MASK51;
    t2 += c;
    c  = t2 >> 51; r2 = (uint64_t)t2 & MASK51;
    t3 += c;
    c  = t3 >> 51; r3 = (uint64_t)t3 & MASK51;
    t4 += c;
    c  = t4 >> 51; r4 = (uint64_t)t4 & MASK51;
    r0 += 19 * (uint64_t)c;

    out[0] = r0; out[1] = r1; out[2] = r2; out[3] = r3; out[4] = r4;
}

/* -------------------------------------------------------------------------
 * fiat_25519_square — field squaring: out = a^2  (mod p)
 *
 * Specialised squaring: uses the identity (a_i * a_j + a_j * a_i) = 2*a_i*a_j
 * for i != j to halve the number of 64-bit multiplications.
 * --------------------------------------------------------------------- */
void fiat_25519_square(
    fiat_25519_tight_field_element out,
    const fiat_25519_loose_field_element a)
{
    uint64_t a0 = a[0], a1 = a[1], a2 = a[2], a3 = a[3], a4 = a[4];

    uint64_t a0_2  = 2 * a0;
    uint64_t a1_2  = 2 * a1;
    uint64_t a1_38 = 38 * a1;   /* 2 * 19 * a1 */
    uint64_t a2_19 = 19 * a2;
    uint64_t a3_19 = 19 * a3;
    uint64_t a4_19 = 19 * a4;
    uint64_t a4_38 = 38 * a4;   /* 2 * 19 * a4 */

    /*
     * t0 = a0^2 + 2*(a1*a4_19*2 + a2*a3_19*2)
     *    = a0^2 + a1_38*a4 + 2*a2*a3_19
     *    -- but simpler to write fully expanded:
     *
     * t0 = a0*a0 + a4_38*a1 + a2_19*a3*2      (cross: a1*a4 + a4*a1 folded)
     * t1 = a0_2*a1 + a4_38*a2 + a3_19*a3
     * t2 = a0_2*a2 + a1*a1 + a4_38*a3
     * t3 = a0_2*a3 + a1_2*a2 + a4_19*a4
     * t4 = a0_2*a4 + a1_2*a3 + a2*a2
     */
    uint128_t t0 = mul64(a0,a0) + mul64(a4_38,a1) + mul64(2*a2_19,a3);
    uint128_t t1 = mul64(a0_2,a1) + mul64(a4_38,a2) + mul64(a3_19,a3);
    uint128_t t2 = mul64(a0_2,a2) + mul64(a1,a1) + mul64(a4_38,a3);
    uint128_t t3 = mul64(a0_2,a3) + mul64(a1_2,a2) + mul64(a4_19,a4);
    uint128_t t4 = mul64(a0_2,a4) + mul64(a1_2,a3) + mul64(a2,a2);

    uint64_t r0, r1, r2, r3, r4;
    uint128_t c;

    c  = t0 >> 51; r0 = (uint64_t)t0 & MASK51;
    t1 += c;
    c  = t1 >> 51; r1 = (uint64_t)t1 & MASK51;
    t2 += c;
    c  = t2 >> 51; r2 = (uint64_t)t2 & MASK51;
    t3 += c;
    c  = t3 >> 51; r3 = (uint64_t)t3 & MASK51;
    t4 += c;
    c  = t4 >> 51; r4 = (uint64_t)t4 & MASK51;
    r0 += 19 * (uint64_t)c;

    out[0] = r0; out[1] = r1; out[2] = r2; out[3] = r3; out[4] = r4;
}

/* -------------------------------------------------------------------------
 * fiat_25519_add — field addition: out = a + b  (loose result)
 *
 * The fiat-crypto convention: add takes two tight inputs and returns a
 * loose result (each limb up to 2^52).  A subsequent carry call is needed
 * before using the result in mul/square.
 * --------------------------------------------------------------------- */
void fiat_25519_add(
    fiat_25519_loose_field_element out,
    const fiat_25519_tight_field_element a,
    const fiat_25519_tight_field_element b)
{
    out[0] = a[0] + b[0];
    out[1] = a[1] + b[1];
    out[2] = a[2] + b[2];
    out[3] = a[3] + b[3];
    out[4] = a[4] + b[4];
}

/* -------------------------------------------------------------------------
 * fiat_25519_sub — field subtraction: out = a - b  (loose result)
 *
 * To avoid underflow, we add a multiple of p before subtracting.
 * The constant 2*p in 51-bit limbs, each limb equal to 2*(2^51 - 1) + ...:
 *   2*p = 2*(2^255 - 19) = 2^256 - 38
 *
 * In the 51-bit representation, 2p has limbs:
 *   limb[0] = 0x3fffffffffff68  (= 2 * (2^51 - 1) + ... — see below)
 *   limb[1..4] = 0x3ffffffffffff8
 *
 * These are the same magic constants used in the HACL* Field51 fsub above.
 * --------------------------------------------------------------------- */
void fiat_25519_sub(
    fiat_25519_loose_field_element out,
    const fiat_25519_tight_field_element a,
    const fiat_25519_tight_field_element b)
{
    /*
     * 2p in 51-bit limbs:
     *   p = 2^255 - 19 = sum_i p_i * 2^(51*i)
     *   2p[0] = 2*(2^51-1) - 2*19 + 2^52 wrapping = 0x3fffffffffff68
     *   2p[1..4] = 0x3ffffffffffff8
     *
     * These ensure a[i] - b[i] + 2p[i] >= 0 for any tight a, b.
     */
    out[0] = a[0] - b[0] + UINT64_C(0x3fffffffffff68);
    out[1] = a[1] - b[1] + UINT64_C(0x3ffffffffffff8);
    out[2] = a[2] - b[2] + UINT64_C(0x3ffffffffffff8);
    out[3] = a[3] - b[3] + UINT64_C(0x3ffffffffffff8);
    out[4] = a[4] - b[4] + UINT64_C(0x3ffffffffffff8);
}

/* -------------------------------------------------------------------------
 * fiat_25519_opp — field negation: out = -a  (loose result)
 *
 * Implemented as fiat_25519_sub(out, zero, a) with zero = {0,0,0,0,0}.
 * We add 2p to avoid underflow, same as sub.
 * --------------------------------------------------------------------- */
void fiat_25519_opp(
    fiat_25519_loose_field_element out,
    const fiat_25519_tight_field_element a)
{
    out[0] = UINT64_C(0x3fffffffffff68) - a[0];
    out[1] = UINT64_C(0x3ffffffffffff8) - a[1];
    out[2] = UINT64_C(0x3ffffffffffff8) - a[2];
    out[3] = UINT64_C(0x3ffffffffffff8) - a[3];
    out[4] = UINT64_C(0x3ffffffffffff8) - a[4];
}

/* -------------------------------------------------------------------------
 * fiat_25519_selectznz — constant-time conditional select
 *
 * out = (cond == 0) ? z : nz
 *
 * cond must be exactly 0 or 1.  The mask trick avoids branches.
 * --------------------------------------------------------------------- */
void fiat_25519_selectznz(
    fiat_25519_tight_field_element out,
    fiat_25519_uint1 cond,
    const fiat_25519_tight_field_element z,
    const fiat_25519_tight_field_element nz)
{
    uint64_t mask = (uint64_t)(-(int64_t)cond); /* 0x0000...0000 or 0xffff...ffff */
    out[0] = z[0] ^ (mask & (z[0] ^ nz[0]));
    out[1] = z[1] ^ (mask & (z[1] ^ nz[1]));
    out[2] = z[2] ^ (mask & (z[2] ^ nz[2]));
    out[3] = z[3] ^ (mask & (z[3] ^ nz[3]));
    out[4] = z[4] ^ (mask & (z[4] ^ nz[4]));
}

/* -------------------------------------------------------------------------
 * fiat_25519_to_bytes — encode a tight field element to 32 bytes (LE)
 *
 * The output is the canonical 32-byte little-endian encoding of the
 * field element (fully reduced modulo p = 2^255 - 19).
 *
 * Algorithm (two-pass reduction):
 *   1. Propagate carries to ensure every limb < 2^51.
 *   2. Conditionally subtract p if the value >= p.
 *   3. Pack the 5×51-bit limbs into 32 bytes (255 bits, LE).
 * --------------------------------------------------------------------- */
void fiat_25519_to_bytes(
    uint8_t out[32],
    const fiat_25519_tight_field_element a)
{
    /* Two-pass carry to ensure canonical tight form. */
    uint64_t x0 = a[0], x1 = a[1], x2 = a[2], x3 = a[3], x4 = a[4];
    uint64_t c;

    /* Pass 1 */
    c = x0 >> 51; x0 &= MASK51; x1 += c;
    c = x1 >> 51; x1 &= MASK51; x2 += c;
    c = x2 >> 51; x2 &= MASK51; x3 += c;
    c = x3 >> 51; x3 &= MASK51; x4 += c;
    c = x4 >> 51; x4 &= MASK51; x0 += 19 * c;

    /* Pass 2 (handles the 19*c wraparound from pass 1) */
    c = x0 >> 51; x0 &= MASK51; x1 += c;
    c = x1 >> 51; x1 &= MASK51; x2 += c;
    c = x2 >> 51; x2 &= MASK51; x3 += c;
    c = x3 >> 51; x3 &= MASK51; x4 += c;
    c = x4 >> 51; x4 &= MASK51; x0 += 19 * c;

    /*
     * Conditional subtraction of p = 2^255 - 19.
     *
     * We compute x - p.  If x >= p, the borrow is 0 and we keep x - p.
     * If x < p, the borrow is 1 and we keep x.
     *
     * p in 51-bit limbs:
     *   p[0] = 2^51 - 19 = 0x7ffffffffffed
     *   p[1..4] = 2^51 - 1 = 0x7ffffffffffff
     *
     * We use unsigned subtraction and borrow-propagation.
     */
    uint64_t m0 = (x0 >= UINT64_C(0x7ffffffffffed)) ? UINT64_MAX : 0;
    uint64_t m1 = (x1 >= MASK51) ? UINT64_MAX : 0;
    uint64_t m2 = (x2 >= MASK51) ? UINT64_MAX : 0;
    uint64_t m3 = (x3 >= MASK51) ? UINT64_MAX : 0;
    uint64_t m4 = (x4 >= MASK51) ? UINT64_MAX : 0;
    uint64_t mask = m0 & m1 & m2 & m3 & m4;

    x0 -= mask & UINT64_C(0x7ffffffffffed);
    x1 -= mask & MASK51;
    x2 -= mask & MASK51;
    x3 -= mask & MASK51;
    x4 -= mask & MASK51;

    /*
     * Pack 5 × 51-bit limbs into 32 bytes (little-endian, 255 bits).
     *
     * Bit layout (bit positions within the 256-bit output):
     *   x0: bits [0..50]    stored starting at bit  0  of byte  0
     *   x1: bits [51..101]  stored starting at bit 51  of byte  6 (bit 3)
     *   x2: bits [102..152] stored starting at bit 102 of byte 12 (bit 6)
     *   x3: bits [153..203] stored starting at bit 153 of byte 19 (bit 1)
     *   x4: bits [204..254] stored starting at bit 204 of byte 25 (bit 4)
     *   bit 255 = 0
     *
     * We pack limbs into four 64-bit LE words and then store byte-by-byte.
     *
     *   w0 = x0 | (x1 << 51)                         covers bits 0..114
     *   w1 = (x1 >> 13) | (x2 << 38)                 covers bits 64..165
     *   w2 = (x2 >> 26) | (x3 << 25)                 covers bits 128..229
     *   w3 = (x3 >> 39) | (x4 << 12)                 covers bits 192..255
     *
     * Each word spans one 64-bit / 8-byte region in the output.
     */
    uint64_t w0 = x0 | (x1 << 51);
    uint64_t w1 = (x1 >> 13) | (x2 << 38);
    uint64_t w2 = (x2 >> 26) | (x3 << 25);
    uint64_t w3 = (x3 >> 39) | (x4 << 12);

    out[ 0] = (uint8_t)(w0 >>  0);
    out[ 1] = (uint8_t)(w0 >>  8);
    out[ 2] = (uint8_t)(w0 >> 16);
    out[ 3] = (uint8_t)(w0 >> 24);
    out[ 4] = (uint8_t)(w0 >> 32);
    out[ 5] = (uint8_t)(w0 >> 40);
    out[ 6] = (uint8_t)(w0 >> 48);
    out[ 7] = (uint8_t)(w0 >> 56);
    out[ 8] = (uint8_t)(w1 >>  0);
    out[ 9] = (uint8_t)(w1 >>  8);
    out[10] = (uint8_t)(w1 >> 16);
    out[11] = (uint8_t)(w1 >> 24);
    out[12] = (uint8_t)(w1 >> 32);
    out[13] = (uint8_t)(w1 >> 40);
    out[14] = (uint8_t)(w1 >> 48);
    out[15] = (uint8_t)(w1 >> 56);
    out[16] = (uint8_t)(w2 >>  0);
    out[17] = (uint8_t)(w2 >>  8);
    out[18] = (uint8_t)(w2 >> 16);
    out[19] = (uint8_t)(w2 >> 24);
    out[20] = (uint8_t)(w2 >> 32);
    out[21] = (uint8_t)(w2 >> 40);
    out[22] = (uint8_t)(w2 >> 48);
    out[23] = (uint8_t)(w2 >> 56);
    out[24] = (uint8_t)(w3 >>  0);
    out[25] = (uint8_t)(w3 >>  8);
    out[26] = (uint8_t)(w3 >> 16);
    out[27] = (uint8_t)(w3 >> 24);
    out[28] = (uint8_t)(w3 >> 32);
    out[29] = (uint8_t)(w3 >> 40);
    out[30] = (uint8_t)(w3 >> 48);
    out[31] = (uint8_t)(w3 >> 56);   /* top bit is 0 since x4 < 2^51, << 12 */
}

/* -------------------------------------------------------------------------
 * fiat_25519_from_bytes — decode 32 bytes (LE) into a tight field element
 *
 * The top bit of in[31] is silently masked (RFC 7748 §5: "implementations
 * MUST mask the most significant bit in the final byte").
 *
 * Algorithm: split the 255 bits across 5 limbs of 51 bits each.
 * --------------------------------------------------------------------- */
void fiat_25519_from_bytes(
    fiat_25519_tight_field_element out,
    const uint8_t in[32])
{
    /*
     * We load the 32 bytes into 4 uint64_t words (little-endian) first,
     * then slice them into 51-bit limbs.
     */
    uint64_t w0, w1, w2, w3;

    /* Load 4 × 8 = 32 bytes as LE uint64 (byte-by-byte for portability). */
    w0  = (uint64_t)in[ 0]
        | ((uint64_t)in[ 1] <<  8)
        | ((uint64_t)in[ 2] << 16)
        | ((uint64_t)in[ 3] << 24)
        | ((uint64_t)in[ 4] << 32)
        | ((uint64_t)in[ 5] << 40)
        | ((uint64_t)in[ 6] << 48)
        | ((uint64_t)in[ 7] << 56);

    w1  = (uint64_t)in[ 8]
        | ((uint64_t)in[ 9] <<  8)
        | ((uint64_t)in[10] << 16)
        | ((uint64_t)in[11] << 24)
        | ((uint64_t)in[12] << 32)
        | ((uint64_t)in[13] << 40)
        | ((uint64_t)in[14] << 48)
        | ((uint64_t)in[15] << 56);

    w2  = (uint64_t)in[16]
        | ((uint64_t)in[17] <<  8)
        | ((uint64_t)in[18] << 16)
        | ((uint64_t)in[19] << 24)
        | ((uint64_t)in[20] << 32)
        | ((uint64_t)in[21] << 40)
        | ((uint64_t)in[22] << 48)
        | ((uint64_t)in[23] << 56);

    w3  = (uint64_t)in[24]
        | ((uint64_t)in[25] <<  8)
        | ((uint64_t)in[26] << 16)
        | ((uint64_t)in[27] << 24)
        | ((uint64_t)in[28] << 32)
        | ((uint64_t)in[29] << 40)
        | ((uint64_t)in[30] << 48)
        | (((uint64_t)in[31] & 0x7f) << 56); /* mask bit 255 per RFC 7748 */

    /*
     * Slice 256 bits into 5 × 51-bit limbs.
     *
     * Limb boundaries (bit offsets from the start of the 256-bit integer):
     *   limb[0]: bits [  0.. 50]   from w0
     *   limb[1]: bits [ 51..101]   from w0 (high 13 bits) + w1 (low 38 bits)
     *   limb[2]: bits [102..152]   from w1 (high 26 bits) + w2 (low 25 bits)
     *   limb[3]: bits [153..203]   from w2 (high 39 bits) + w3 (low 12 bits)
     *   limb[4]: bits [204..254]   from w3 (high 52 bits → 51 bits after mask)
     */
    out[0] =  w0          & MASK51;
    out[1] = (w0 >> 51 | w1 << 13) & MASK51;
    out[2] = (w1 >> 38 | w2 << 26) & MASK51;
    out[3] = (w2 >> 25 | w3 << 39) & MASK51;
    out[4] = (w3 >> 12)             & MASK51;
}
