-- SPDX-License-Identifier: Apache-2.0
module UmbraVox.TUI.EmojiPicker
    ( emojiCategories
    , emojiByCategory
    , searchEmoji
    , emojiPage
    , emojiPageCount
    , selectorKeys
    ) where

import Data.Char (toLower)
import Data.List (isInfixOf)

-- | Names of all emoji categories, in display order.
emojiCategories :: [String]
emojiCategories =
    [ "Smileys", "People", "Animals", "Food"
    , "Travel", "Objects", "Symbols", "Flags"
    ]

-- | Each entry is (emoji character(s), lowercase name/description).
type EmojiEntry = (String, String)

-- | Page layout: 6 rows x 6 columns = 36 per page.
pageSize :: Int
pageSize = 36

-- | Selector keys: A-Z then 0-9 (36 total).
selectorKeys :: String
selectorKeys = ['A'..'Z'] ++ ['0'..'9']

-- | All emoji for a given category index (0-based), or [] for out-of-range.
emojiByCategory :: Int -> [EmojiEntry]
emojiByCategory 0 = smileys
emojiByCategory 1 = people
emojiByCategory 2 = animals
emojiByCategory 3 = food
emojiByCategory 4 = travel
emojiByCategory 5 = objects
emojiByCategory 6 = symbols
emojiByCategory 7 = flags
emojiByCategory _ = []

-- | Search emoji across all categories by name substring.
-- Returns matching entries from all categories in order.
searchEmoji :: String -> [EmojiEntry]
searchEmoji q
    | null q = concatMap emojiByCategory [0 .. length emojiCategories - 1]
    | otherwise =
        let needle = map toLower q
            allEntries = concatMap emojiByCategory [0 .. length emojiCategories - 1]
        in filter (\(_, name) -> needle `isInfixOf` name) allEntries

-- | Total number of pages for a given list of emoji entries.
emojiPageCount :: [EmojiEntry] -> Int
emojiPageCount entries =
    let n = length entries
    in if n == 0 then 1 else (n + pageSize - 1) `div` pageSize

-- | Slice one page (0-based) from a list of emoji entries.
-- Returns exactly up to 36 entries.
emojiPage :: Int -> [EmojiEntry] -> [EmojiEntry]
emojiPage pageIx entries =
    let start = pageIx * pageSize
    in take pageSize (drop start entries)

-- -------------------------------------------------------------------------
-- Emoji data
-- -------------------------------------------------------------------------

smileys :: [EmojiEntry]
smileys =
    [ ("\x1F600", "grinning face")
    , ("\x1F601", "beaming face with smiling eyes")
    , ("\x1F602", "face with tears of joy")
    , ("\x1F923", "rolling on the floor laughing")
    , ("\x1F603", "grinning face with big eyes")
    , ("\x1F604", "grinning face with smiling eyes")
    , ("\x1F605", "grinning face with sweat")
    , ("\x1F606", "grinning squinting face")
    , ("\x1F609", "winking face")
    , ("\x1F60A", "smiling face with smiling eyes")
    , ("\x1F60B", "face savoring food")
    , ("\x1F60E", "smiling face with sunglasses")
    , ("\x1F60D", "smiling face with heart-eyes")
    , ("\x1F970", "smiling face with hearts")
    , ("\x1F618", "face blowing a kiss")
    , ("\x1F617", "kissing face")
    , ("\x1F619", "kissing face with smiling eyes")
    , ("\x1F61A", "kissing face with closed eyes")
    , ("\x1F642", "slightly smiling face")
    , ("\x1F917", "hugging face")
    , ("\x1F929", "star-struck")
    , ("\x1F973", "partying face")
    , ("\x1F60F", "smirking face")
    , ("\x1F636", "face without mouth")
    , ("\x1F610", "neutral face")
    , ("\x1F611", "expressionless face")
    , ("\x1F612", "unamused face")
    , ("\x1F61E", "disappointed face")
    , ("\x1F614", "pensive face")
    , ("\x1F61F", "worried face")
    , ("\x1F615", "confused face")
    , ("\x1F643", "upside-down face")
    , ("\x1F924", "drooling face")
    , ("\x1F620", "angry face")
    , ("\x1F621", "pouting face")
    , ("\x1F92C", "face with symbols on mouth")
    , ("\x1F608", "smiling face with horns")
    , ("\x1F47F", "angry face with horns")
    , ("\x1F480", "skull")
    , ("\x2620\xFE0F", "skull and crossbones")
    , ("\x1F4A9", "pile of poo")
    , ("\x1F921", "clown face")
    , ("\x1F479", "ogre")
    , ("\x1F47A", "goblin")
    , ("\x1F47B", "ghost")
    , ("\x1F47D", "alien")
    , ("\x1F47E", "alien monster")
    , ("\x1F916", "robot")
    , ("\x1F63A", "grinning cat")
    , ("\x1F638", "grinning cat with smiling eyes")
    , ("\x1F639", "cat with tears of joy")
    , ("\x1F63B", "smiling cat with heart-eyes")
    , ("\x1F63C", "cat with wry smile")
    , ("\x1F63D", "kissing cat")
    , ("\x1F640", "weary cat")
    , ("\x1F63F", "crying cat")
    , ("\x1F63E", "pouting cat")
    , ("\x1F648", "see-no-evil monkey")
    , ("\x1F649", "hear-no-evil monkey")
    , ("\x1F64A", "speak-no-evil monkey")
    , ("\x1F631", "face screaming in fear")
    , ("\x1F628", "fearful face")
    , ("\x1F630", "anxious face with sweat")
    , ("\x1F622", "crying face")
    , ("\x1F62D", "loudly crying face")
    ]

people :: [EmojiEntry]
people =
    [ ("\x1F44B", "waving hand")
    , ("\x1F91A", "raised back of hand")
    , ("\x1F590\xFE0F", "hand with fingers splayed")
    , ("\x270B", "raised hand")
    , ("\x1F596", "vulcan salute")
    , ("\x1F44F", "clapping hands")
    , ("\x1F64C", "raising hands")
    , ("\x1F450", "open hands")
    , ("\x1F932", "palms up together")
    , ("\x1F91D", "handshake")
    , ("\x1F44D", "thumbs up")
    , ("\x1F44E", "thumbs down")
    , ("\x270A", "raised fist")
    , ("\x1F44A", "oncoming fist")
    , ("\x1F91B", "left-facing fist")
    , ("\x1F91C", "right-facing fist")
    , ("\x1F91E", "crossed fingers")
    , ("\x1F918", "sign of the horns")
    , ("\x1F919", "call me hand")
    , ("\x1F448", "backhand index pointing left")
    , ("\x1F449", "backhand index pointing right")
    , ("\x1F446", "backhand index pointing up")
    , ("\x1F595", "middle finger")
    , ("\x1F447", "backhand index pointing down")
    , ("\x261D\xFE0F", "index pointing up")
    , ("\x1F4AA", "flexed biceps")
    , ("\x1F9B5", "leg")
    , ("\x1F9B6", "foot")
    , ("\x1F442", "ear")
    , ("\x1F443", "nose")
    , ("\x1F9E0", "brain")
    , ("\x1F9B7", "tooth")
    , ("\x1F440", "eyes")
    , ("\x1F441\xFE0F", "eye")
    , ("\x1F445", "tongue")
    , ("\x1F444", "mouth")
    , ("\x1F476", "baby")
    , ("\x1F9D2", "child")
    , ("\x1F466", "boy")
    , ("\x1F467", "girl")
    , ("\x1F9D1", "person")
    , ("\x1F471", "person blond hair")
    , ("\x1F468", "man")
    , ("\x1F9D4", "man beard")
    , ("\x1F469", "woman")
    , ("\x1F475", "old woman")
    , ("\x1F474", "old man")
    , ("\x1F46E", "police officer")
    , ("\x1F575\xFE0F", "detective")
    , ("\x1F482", "guard")
    , ("\x1F977", "ninja")
    , ("\x1F477", "construction worker")
    , ("\x1FAF1", "handshake hands")
    , ("\x1F91F", "love-you gesture")
    , ("\x1F590\xFE0F", "raised hand five fingers")
    , ("\x1F64F", "folded hands")
    , ("\x1F485", "nail polish")
    , ("\x1F933", "selfie")
    , ("\x1F4AA", "strong arm")
    , ("\x1F9B8", "superhero")
    , ("\x1F9B9", "supervillain")
    , ("\x1F9D9", "mage")
    , ("\x1F9DA", "fairy")
    , ("\x1F9DB", "vampire")
    ]

animals :: [EmojiEntry]
animals =
    [ ("\x1F436", "dog face")
    , ("\x1F431", "cat face")
    , ("\x1F42D", "mouse face")
    , ("\x1F439", "hamster")
    , ("\x1F430", "rabbit face")
    , ("\x1F98A", "fox")
    , ("\x1F43B", "bear")
    , ("\x1F43C", "panda")
    , ("\x1F428", "koala")
    , ("\x1F42F", "tiger face")
    , ("\x1F981", "lion")
    , ("\x1F42E", "cow face")
    , ("\x1F437", "pig face")
    , ("\x1F43D", "pig nose")
    , ("\x1F438", "frog")
    , ("\x1F435", "monkey face")
    , ("\x1F648", "see-no-evil monkey")
    , ("\x1F426", "bird")
    , ("\x1F427", "penguin")
    , ("\x1F54A\xFE0F", "dove")
    , ("\x1F985", "eagle")
    , ("\x1F986", "duck")
    , ("\x1F989", "owl")
    , ("\x1F40D", "snake")
    , ("\x1F98E", "lizard")
    , ("\x1F432", "dragon face")
    , ("\x1F409", "dragon")
    , ("\x1F433", "spouting whale")
    , ("\x1F40B", "whale")
    , ("\x1F42C", "dolphin")
    , ("\x1F41F", "fish")
    , ("\x1F420", "tropical fish")
    , ("\x1F421", "blowfish")
    , ("\x1F988", "shark")
    , ("\x1F419", "octopus")
    , ("\x1F41A", "spiral shell")
    , ("\x1F40C", "snail")
    , ("\x1F98B", "butterfly")
    , ("\x1F41B", "bug")
    , ("\x1F41D", "honeybee")
    , ("\x1FAB1", "fly")
    , ("\x1F41E", "lady beetle")
    , ("\x1F99F", "mosquito")
    , ("\x1F40E", "horse")
    , ("\x1F984", "unicorn")
    , ("\x1F993", "zebra")
    , ("\x1F98C", "deer")
    , ("\x1F42A", "camel")
    , ("\x1F992", "giraffe")
    , ("\x1F418", "elephant")
    , ("\x1F99B", "hippopotamus")
    , ("\x1F98F", "rhinoceros")
    , ("\x1F42B", "two-hump camel")
    , ("\x1F999", "llama")
    , ("\x1F9A1", "beaver")
    , ("\x1F410", "goat")
    , ("\x1F411", "ewe")
    , ("\x1F412", "monkey")
    , ("\x1F413", "rooster")
    , ("\x1F414", "chicken")
    , ("\x1F423", "hatching chick")
    , ("\x1F424", "baby chick")
    , ("\x1F425", "front-facing baby chick")
    , ("\x1F415", "dog")
    , ("\x1F98D", "gorilla")
    ]

food :: [EmojiEntry]
food =
    [ ("\x1F34E", "red apple")
    , ("\x1F34F", "green apple")
    , ("\x1F350", "pear")
    , ("\x1F34A", "tangerine")
    , ("\x1F34B", "lemon")
    , ("\x1F34C", "banana")
    , ("\x1F349", "watermelon")
    , ("\x1F347", "grapes")
    , ("\x1F353", "strawberry")
    , ("\x1FAD0", "blueberries")
    , ("\x1F352", "cherries")
    , ("\x1F351", "peach")
    , ("\x1F96D", "mango")
    , ("\x1F34D", "pineapple")
    , ("\x1F965", "coconut")
    , ("\x1F95D", "kiwi fruit")
    , ("\x1F345", "tomato")
    , ("\x1F965", "coconut")
    , ("\x1F346", "eggplant")
    , ("\x1F955", "carrot")
    , ("\x1F33D", "ear of corn")
    , ("\x1F336\xFE0F", "hot pepper")
    , ("\x1F952", "cucumber")
    , ("\x1F966", "leafy green")
    , ("\x1F96C", "leafy vegetable")
    , ("\x1F9C5", "onion")
    , ("\x1F9C4", "garlic")
    , ("\x1F954", "potato")
    , ("\x1F360", "roasted sweet potato")
    , ("\x1F35E", "bread")
    , ("\x1F950", "croissant")
    , ("\x1F956", "baguette bread")
    , ("\x1FAD3", "flatbread")
    , ("\x1F968", "pretzel")
    , ("\x1F96F", "bagel")
    , ("\x1F9C7", "waffle")
    , ("\x1F9C0", "cheese wedge")
    , ("\x1F356", "meat on bone")
    , ("\x1F357", "poultry leg")
    , ("\x1F969", "cut of meat")
    , ("\x1F373", "cooking")
    , ("\x1F354", "hamburger")
    , ("\x1F35F", "french fries")
    , ("\x1F355", "pizza")
    , ("\x1F32D", "hot dog")
    , ("\x1F96A", "sandwich")
    , ("\x1F32E", "taco")
    , ("\x1F32F", "burrito")
    , ("\x1FAD4", "tamale")
    , ("\x1F959", "stuffed flatbread")
    , ("\x1F9C6", "falafel")
    , ("\x1F95A", "egg")
    , ("\x1F372", "pot of food")
    , ("\x1FAD5", "fondue")
    , ("\x1F365", "fish cake with swirl")
    , ("\x1F958", "shallow pan of food")
    , ("\x1F35C", "steaming bowl")
    , ("\x1F363", "sushi")
    , ("\x1F371", "bento box")
    , ("\x1F364", "fried shrimp")
    , ("\x1F362", "oden")
    , ("\x1FAD1", "fondue pot")
    , ("\x1F366", "soft ice cream")
    , ("\x1F367", "shaved ice")
    , ("\x1F368", "ice cream")
    ]

travel :: [EmojiEntry]
travel =
    [ ("\x1F697", "automobile")
    , ("\x1F695", "taxi")
    , ("\x1F68C", "bus")
    , ("\x1F68E", "trolleybus")
    , ("\x1F3CE\xFE0F", "racing car")
    , ("\x1F699", "sport utility vehicle")
    , ("\x1F3CD\xFE0F", "motorcycle")
    , ("\x1F6B2", "bicycle")
    , ("\x1F6F4", "kick scooter")
    , ("\x1F6F5", "motor scooter")
    , ("\x1F68D", "minibus")
    , ("\x1F68B", "articulated lorry")
    , ("\x1F69A", "delivery truck")
    , ("\x1F691", "ambulance")
    , ("\x1F692", "fire engine")
    , ("\x1F693", "police car")
    , ("\x1F6A3", "rowboat")
    , ("\x26F5", "sailboat")
    , ("\x1F6E5\xFE0F", "motor boat")
    , ("\x1F6A4", "speedboat")
    , ("\x26F4\xFE0F", "ferry")
    , ("\x1F6F3\xFE0F", "passenger ship")
    , ("\x1F6A2", "ship")
    , ("\x2708\xFE0F", "airplane")
    , ("\x1F6E9\xFE0F", "small airplane")
    , ("\x1F6EB", "airplane departure")
    , ("\x1F6EC", "airplane arrival")
    , ("\x1FA82", "parachute")
    , ("\x1F681", "helicopter")
    , ("\x1F69F", "suspension railway")
    , ("\x1F6A0", "mountain cableway")
    , ("\x1F6A1", "aerial tramway")
    , ("\x1F6F0\xFE0F", "satellite")
    , ("\x1F680", "rocket")
    , ("\x1F6F8", "flying saucer")
    , ("\x1F4BA", "seat")
    , ("\x1F6D1", "stop sign")
    , ("\x26D4", "no entry")
    , ("\x26A0\xFE0F", "warning")
    , ("\x1F6A7", "construction")
    , ("\x26F3", "flag in hole")
    , ("\x1F3C1", "chequered flag")
    , ("\x1F3DB\xFE0F", "classical building")
    , ("\x1F3D7\xFE0F", "building construction")
    , ("\x1F3E0", "house")
    , ("\x1F3E1", "house with garden")
    , ("\x1F3E2", "office building")
    , ("\x1F3E3", "japanese post office")
    , ("\x1F3E4", "post office")
    , ("\x1F3E5", "hospital")
    , ("\x1F3E6", "bank")
    , ("\x1F3E8", "hotel")
    , ("\x1F3E9", "love hotel")
    , ("\x1F3EA", "convenience store")
    , ("\x1F3EB", "school")
    , ("\x1F3EC", "department store")
    , ("\x1F3ED", "factory")
    , ("\x1F5FC", "tokyo tower")
    , ("\x1F5FD", "statue of liberty")
    , ("\x26EA", "church")
    , ("\x1F54C", "mosque")
    , ("\x1F6D5", "hindu temple")
    , ("\x1F54D", "synagogue")
    , ("\x26E9\xFE0F", "shinto shrine")
    , ("\x1F5FE", "map of japan")
    , ("\x26F0\xFE0F", "mountain")
    ]

objects :: [EmojiEntry]
objects =
    [ ("\x231A", "watch")
    , ("\x1F4F1", "mobile phone")
    , ("\x1F4BB", "laptop")
    , ("\x1F5A5\xFE0F", "desktop computer")
    , ("\x1F5A8\xFE0F", "printer")
    , ("\x1F5B1\xFE0F", "computer mouse")
    , ("\x1F5B2\xFE0F", "trackball")
    , ("\x1F4BD", "computer disk")
    , ("\x1F4BE", "floppy disk")
    , ("\x1F4BF", "optical disk")
    , ("\x1F4C0", "dvd")
    , ("\x1F9EE", "abacus")
    , ("\x1F3A5", "movie camera")
    , ("\x1F4F7", "camera")
    , ("\x1F4F8", "camera with flash")
    , ("\x1F4F9", "video camera")
    , ("\x1F4FC", "videocassette")
    , ("\x1F4DE", "telephone receiver")
    , ("\x260E\xFE0F", "telephone")
    , ("\x1F4DF", "pager")
    , ("\x1F4E0", "fax machine")
    , ("\x1F50B", "battery")
    , ("\x1F50C", "electric plug")
    , ("\x1F4A1", "light bulb")
    , ("\x1F526", "flashlight")
    , ("\x1F56F\xFE0F", "candle")
    , ("\x1F9F1", "brick")
    , ("\x1FA99", "coin")
    , ("\x1F4B0", "money bag")
    , ("\x1F4B4", "yen banknote")
    , ("\x1F4B5", "dollar banknote")
    , ("\x1F4B6", "euro banknote")
    , ("\x1F4B7", "pound banknote")
    , ("\x1F4B8", "money with wings")
    , ("\x1F4B3", "credit card")
    , ("\x1F48E", "gem stone")
    , ("\x1F527", "wrench")
    , ("\x1F528", "hammer")
    , ("\x1F6E0\xFE0F", "hammer and wrench")
    , ("\x2694\xFE0F", "crossed swords")
    , ("\x1F52B", "pistol")
    , ("\x1F6E1\xFE0F", "shield")
    , ("\x1F512", "locked")
    , ("\x1F513", "unlocked")
    , ("\x1F511", "key")
    , ("\x1F5DD\xFE0F", "old key")
    , ("\x1F6AA", "door")
    , ("\x1F6CB\xFE0F", "couch and lamp")
    , ("\x1FA91", "chair")
    , ("\x1F6CF\xFE0F", "bed")
    , ("\x1F9F9", "broom")
    , ("\x1F9FA", "basket")
    , ("\x1FAA3", "bucket")
    , ("\x1F9FB", "roll of paper")
    , ("\x1F9FC", "soap")
    , ("\x1F9FD", "sponge")
    , ("\x1F9EF", "fire extinguisher")
    , ("\x1F6D2", "shopping cart")
    , ("\x1F6AC", "cigarette")
    , ("\x26B0\xFE0F", "coffin")
    , ("\x1F9FF", "nazar amulet")
    , ("\x1F488", "barber pole")
    , ("\x1FA97", "accordion")
    , ("\x1F3B8", "guitar")
    , ("\x1F3B9", "musical keyboard")
    ]

symbols :: [EmojiEntry]
symbols =
    [ ("\x2764\xFE0F", "red heart")
    , ("\x1F9E1", "orange heart")
    , ("\x1F49B", "yellow heart")
    , ("\x1F49A", "green heart")
    , ("\x1F499", "blue heart")
    , ("\x1F49C", "purple heart")
    , ("\x1F5A4", "black heart")
    , ("\x1F90D", "white heart")
    , ("\x1F90E", "brown heart")
    , ("\x1F496", "sparkling heart")
    , ("\x1F497", "growing heart")
    , ("\x1F498", "heart with arrow")
    , ("\x1F49D", "heart with ribbon")
    , ("\x1F49E", "revolving hearts")
    , ("\x1F49F", "heart decoration")
    , ("\x2763\xFE0F", "heart exclamation")
    , ("\x1F494", "broken heart")
    , ("\x2665\xFE0F", "heart suit")
    , ("\x2660\xFE0F", "spade suit")
    , ("\x2666\xFE0F", "diamond suit")
    , ("\x2663\xFE0F", "club suit")
    , ("\x2B50", "star")
    , ("\x1F31F", "glowing star")
    , ("\x2728", "sparkles")
    , ("\x1F4AB", "dizzy")
    , ("\x1F4A5", "collision")
    , ("\x1F4A6", "droplet")
    , ("\x1F4A7", "sweat droplets")
    , ("\x1F525", "fire")
    , ("\x1F4A8", "dashing away")
    , ("\x1F300", "cyclone")
    , ("\x1F308", "rainbow")
    , ("\x26A1", "high voltage")
    , ("\x2600\xFE0F", "sun")
    , ("\x1F31E", "sun with face")
    , ("\x1F315", "full moon")
    , ("\x1F319", "crescent moon")
    , ("\x2744\xFE0F", "snowflake")
    , ("\x2603\xFE0F", "snowman")
    , ("\x26C5", "sun behind cloud")
    , ("\x1F4AF", "hundred points")
    , ("\x2705", "check mark button")
    , ("\x274C", "cross mark")
    , ("\x274E", "cross mark button")
    , ("\x2714\xFE0F", "check mark")
    , ("\x26D4", "no entry")
    , ("\x1F6AB", "prohibited")
    , ("\x26A0\xFE0F", "warning")
    , ("\x267B\xFE0F", "recycling symbol")
    , ("\x2622\xFE0F", "radioactive")
    , ("\x2623\xFE0F", "biohazard")
    , ("\x269B\xFE0F", "atom symbol")
    , ("\x262E\xFE0F", "peace symbol")
    , ("\x271D\xFE0F", "latin cross")
    , ("\x2626\xFE0F", "orthodox cross")
    , ("\x2627\xFE0F", "star and crescent")
    , ("\x2764\xFE0F\x200D\x1F525", "heart on fire")
    , ("\x1F4AC", "speech bubble")
    , ("\x1F4AD", "thought balloon")
    , ("\x1F4A4", "zzz")
    , ("\x1F4A2", "anger symbol")
    , ("\x1F4A3", "bomb")
    , ("\x1F4B1", "currency exchange")
    , ("\x1F199", "up button")
    , ("\x1F51D", "top arrow")
    , ("\x1F197", "ok button")
    ]

flags :: [EmojiEntry]
flags =
    [ ("\x1F3F4", "black flag")
    , ("\x1F3F3\xFE0F", "white flag")
    , ("\x1F3F3\xFE0F\x200D\x1F308", "rainbow flag")
    , ("\x1F3F3\xFE0F\x200D\x26A7\xFE0F", "transgender flag")
    , ("\x1F3C1", "chequered flag")
    , ("\x1F6A9", "triangular flag")
    , ("\x1F38C", "crossed flags")
    , ("\x1F1FA\x1F1F8", "united states flag")
    , ("\x1F1EC\x1F1E7", "united kingdom flag")
    , ("\x1F1E8\x1F1E6", "canada flag")
    , ("\x1F1E6\x1F1FA", "australia flag")
    , ("\x1F1E9\x1F1EA", "germany flag")
    , ("\x1F1EB\x1F1F7", "france flag")
    , ("\x1F1EE\x1F1F9", "italy flag")
    , ("\x1F1EF\x1F1F5", "japan flag")
    , ("\x1F1F0\x1F1F7", "south korea flag")
    , ("\x1F1E8\x1F1F3", "china flag")
    , ("\x1F1F7\x1F1FA", "russia flag")
    , ("\x1F1E7\x1F1F7", "brazil flag")
    , ("\x1F1EE\x1F1F3", "india flag")
    , ("\x1F1F2\x1F1FD", "mexico flag")
    , ("\x1F1EE\x1F1E9", "indonesia flag")
    , ("\x1F1F8\x1F1E6", "saudi arabia flag")
    , ("\x1F1F9\x1F1F7", "turkey flag")
    , ("\x1F1F3\x1F1EC", "nigeria flag")
    , ("\x1F1F3\x1F1F1", "netherlands flag")
    , ("\x1F1E8\x1F1ED", "switzerland flag")
    , ("\x1F1E6\x1F1F7", "argentina flag")
    , ("\x1F1E7\x1F1EA", "belgium flag")
    , ("\x1F1F8\x1F1EA", "sweden flag")
    , ("\x1F1F3\x1F1F4", "norway flag")
    , ("\x1F1E9\x1F1F0", "denmark flag")
    , ("\x1F1F5\x1F1F1", "poland flag")
    , ("\x1F1FA\x1F1E6", "ukraine flag")
    , ("\x1F1EE\x1F1F1", "israel flag")
    , ("\x1F1FA\x1F1F3", "united nations flag")
    , ("\x1F1EA\x1F1FA", "european union flag")
    , ("\x1F1F5\x1F1F9", "portugal flag")
    , ("\x1F1EC\x1F1F7", "greece flag")
    , ("\x1F1E8\x1F1FF", "czech republic flag")
    , ("\x1F1EB\x1F1EE", "finland flag")
    , ("\x1F1E6\x1F1F9", "austria flag")
    , ("\x1F1F8\x1F1EC", "singapore flag")
    , ("\x1F1F3\x1F1FF", "new zealand flag")
    , ("\x1F1FF\x1F1E6", "south africa flag")
    , ("\x1F1E6\x1F1EA", "united arab emirates flag")
    , ("\x1F1F9\x1F1ED", "thailand flag")
    , ("\x1F1F5\x1F1ED", "philippines flag")
    , ("\x1F1F2\x1F1FE", "malaysia flag")
    , ("\x1F1FB\x1F1F3", "vietnam flag")
    , ("\x1F1EE\x1F1F6", "iraq flag")
    , ("\x1F1EE\x1F1F7", "iran flag")
    , ("\x1F1E8\x1F1F4", "colombia flag")
    , ("\x1F1E8\x1F1ED", "chile flag")
    , ("\x1F1F5\x1F1EA", "peru flag")
    , ("\x1F1EB\x1F1EE", "finland flag")
    , ("\x1F1F3\x1F1EC", "nigeria flag")
    , ("\x1F1EA\x1F1EC", "egypt flag")
    , ("\x1F1F0\x1F1EA", "kenya flag")
    , ("\x1F1EC\x1F1ED", "ghana flag")
    , ("\x1F1F9\x1F1F3", "tanzania flag")
    , ("\x1F1EA\x1F1F9", "ethiopia flag")
    , ("\x1F1F2\x1F1E6", "morocco flag")
    , ("\x1F1E8\x1F1EE", "ivory coast flag")
    ]
