-- SPDX-License-Identifier: Apache-2.0
-- | ML-KEM-768 KAT test using Kyber768 reference vectors.
-- Vectors are generated by: ./uv vm kyber generate-kat
-- which commits them to test/vectors/nist/mlkem768-kat.json.
module Test.Crypto.Vectors.MLKEM_KAT (runTests) where

import Data.List (isPrefixOf, tails, stripPrefix)
import qualified Data.ByteString as BS
import System.Directory (doesFileExist)

import Test.Util (hexDecode, hexEncode)
import UmbraVox.Crypto.MLKEM
    ( MLKEMEncapKey(..)
    , MLKEMDecapKey(..)
    , MLKEMCiphertext(..)
    , mlkemEncaps
    , mlkemDecaps
    )

------------------------------------------------------------------------
-- Entry point
------------------------------------------------------------------------

runTests :: IO Bool
runTests = do
    let path = "test/vectors/nist/mlkem768-kat.json"
    exists <- doesFileExist path
    if not exists
        then do
            putStrLn "[MLKEM-KAT] SKIP: test/vectors/nist/mlkem768-kat.json not found"
            putStrLn "[MLKEM-KAT] Run: ./uv vm kyber generate-kat to populate"
            pure True
        else do
            r1 <- testDecapsKAT path
            r2 <- testEncapsRoundTrip path
            pure (r1 && r2)

------------------------------------------------------------------------
-- Sub-test 1: Decaps KAT
--
-- Finding:     Oracle VM produces deterministic KAT vectors with known
--              expected shared secrets.
-- Vulnerability: Any divergence between the UmbraVOX MLKEM decapsulation
--              and the reference implementation would indicate a bug.
-- Fix:         Load committed oracle vectors and verify decapsulation
--              output matches the expected shared secret for each vector.
-- Verified:    Passes when ./uv vm kyber generate-kat has been run.
------------------------------------------------------------------------

testDecapsKAT :: FilePath -> IO Bool
testDecapsKAT path = do
    putStrLn "[MLKEM-KAT] Running decaps KAT..."
    content <- readFile path
    let vecs = parseKATVectors content
    if null vecs
        then do
            putStrLn "  [MLKEM-KAT] FAIL: no vectors parsed from file"
            pure False
        else do
            results <- mapM checkDecaps vecs
            let passed = length (filter id results)
                total  = length results
            putStrLn $ "  [MLKEM-KAT] decaps KAT: " ++ show passed ++ "/" ++ show total ++ " passed."
            pure (and results)
  where
    checkDecaps (vecId, _ek, dk, ct, ss) = do
        let ssDecaps = mlkemDecaps (MLKEMDecapKey dk) (MLKEMCiphertext ct)
        if ssDecaps == ss
            then putStrLn ("    PASS: decaps " ++ vecId) >> pure True
            else do
                putStrLn ("    FAIL: decaps " ++ vecId)
                putStrLn $ "      expected: " ++ hexEncode ss
                putStrLn $ "      actual:   " ++ hexEncode ssDecaps
                pure False

------------------------------------------------------------------------
-- Sub-test 2: Encaps round-trip
--
-- Finding:     Using oracle key material, a fresh encapsulation followed
--              by decapsulation must produce the same shared secret.
-- Vulnerability: A broken encapsulation would produce a shared secret
--              that decapsulation cannot verify, breaking the KEM.
-- Fix:         Round-trip test using oracle public keys ensures both
--              directions are mutually consistent.
-- Verified:    Passes when ./uv vm kyber generate-kat has been run.
------------------------------------------------------------------------

testEncapsRoundTrip :: FilePath -> IO Bool
testEncapsRoundTrip path = do
    putStrLn "[MLKEM-KAT] Running encaps round-trip..."
    content <- readFile path
    let vecs = parseKATVectors content
    if null vecs
        then do
            putStrLn "  [MLKEM-KAT] FAIL: no vectors parsed from file"
            pure False
        else do
            results <- mapM checkRoundTrip vecs
            let passed = length (filter id results)
                total  = length results
            putStrLn $ "  [MLKEM-KAT] encaps round-trip: " ++ show passed ++ "/" ++ show total ++ " passed."
            pure (and results)
  where
    -- Fixed 32-byte message for deterministic encapsulation
    fixedM :: BS.ByteString
    fixedM = BS.replicate 32 0x42

    checkRoundTrip (vecId, ek, dk, _ct, _ss) = do
        let (ct2, ss2) = mlkemEncaps (MLKEMEncapKey ek) fixedM
            ss3        = mlkemDecaps (MLKEMDecapKey dk) ct2
        if ss2 == ss3
            then putStrLn ("    PASS: round-trip " ++ vecId) >> pure True
            else do
                putStrLn ("    FAIL: round-trip " ++ vecId)
                putStrLn $ "      encaps ss: " ++ hexEncode ss2
                putStrLn $ "      decaps ss: " ++ hexEncode ss3
                pure False

------------------------------------------------------------------------
-- JSON parser (hand-rolled, no aeson)
------------------------------------------------------------------------

-- | Parse the KAT JSON and return a list of
-- (id, encap_key, decap_key, ciphertext, shared_secret) tuples,
-- all decoded from hex.
--
-- Handles the schema:
--   {"schema":"...","primitive":"...","vectors":[
--     {"id":"...","encap_key_hex":"...","decap_key_hex":"...","ciphertext_hex":"...","shared_secret_hex":"..."},
--     ...
--   ]}
parseKATVectors :: String
                -> [(String, BS.ByteString, BS.ByteString, BS.ByteString, BS.ByteString)]
parseKATVectors content =
    let objs = extractVectorObjects content
    in  [ (vecId, ek, dk, ct, ss)
        | obj  <- objs
        , let vecId = extractStr' "id"               obj
        , let ek    = hexDecode (extractStr' "encap_key_hex"    obj)
        , let dk    = hexDecode (extractStr' "decap_key_hex"    obj)
        , let ct    = hexDecode (extractStr' "ciphertext_hex"   obj)
        , let ss    = hexDecode (extractStr' "shared_secret_hex" obj)
        , not (null vecId)
        , not (BS.null ek)
        , not (BS.null dk)
        , not (BS.null ct)
        , not (BS.null ss)
        ]

-- | Extract the string value of @"key": "value"@ (or @"key":"value"@).
-- Returns empty string if not found.
extractStr' :: String -> String -> String
extractStr' key text =
    -- Try both @"key": "@ (with space) and @"key":"@ (without space)
    case tryPrefix ("\"" ++ key ++ "\": \"") text of
        Just v  -> v
        Nothing ->
            case tryPrefix ("\"" ++ key ++ "\":\"") text of
                Just v  -> v
                Nothing -> ""
  where
    tryPrefix :: String -> String -> Maybe String
    tryPrefix marker t =
        case break (isPrefixOf marker) (tails t) of
            (_, [])  -> Nothing
            (_, s:_) ->
                case stripPrefix marker s of
                    Nothing   -> Nothing
                    Just rest -> Just (takeWhile (/= '"') rest)

-- | Extract all @{...}@ objects from the @"vectors"@ array in the JSON string.
extractVectorObjects :: String -> [String]
extractVectorObjects input =
    let afterVectors = dropUntilPrefix "\"vectors\"" input
        afterBracket = dropUntilPrefix "[" afterVectors
    in  collectObjects afterBracket

-- | Drop characters until the given prefix is found, then drop the prefix too.
dropUntilPrefix :: String -> String -> String
dropUntilPrefix _   [] = []
dropUntilPrefix pfx s@(_:rest)
    | take (length pfx) s == pfx = drop (length pfx) s
    | otherwise                  = dropUntilPrefix pfx rest

-- | Collect all top-level @{...}@ objects from a JSON array body.
collectObjects :: String -> [String]
collectObjects [] = []
collectObjects ('{':rest) =
    let (obj, remaining) = extractBalanced 1 ['{'] rest
    in  obj : collectObjects remaining
collectObjects (_:rest) = collectObjects rest

-- | Extract a balanced @{...}@ object.
-- Depth starts at 1 (opening @{@ already consumed).
-- Returns (object_string, remaining_input).
extractBalanced :: Int -> String -> String -> (String, String)
extractBalanced 0 acc rest    = (reverse acc, rest)
extractBalanced _ acc []      = (reverse acc, [])
extractBalanced depth acc (c:cs)
    | c == '{' = extractBalanced (depth + 1) (c:acc) cs
    | c == '}' = extractBalanced (depth - 1) (c:acc) cs
    | otherwise = extractBalanced depth      (c:acc) cs
