module Main (main) where

import System.Directory (doesDirectoryExist, listDirectory)
import System.FilePath ((</>), takeExtension)
import qualified CryptoGen
import qualified CBORGen
import qualified FSMGen
import qualified TestGen

-- | Code generator entry point.
-- Reads all .spec, .fsm, and .schema files from codegen/Specs/
-- and writes generated Haskell modules to src/UmbraVox/ and test/Test/.
--
-- Generated by UmbraVox.CodeGen v0.1.0
-- TQL-1 qualified artifact (DO-330)
main :: IO ()
main = do
    let specsDir = "codegen/Specs"
    exists <- doesDirectoryExist specsDir
    if not exists
        then putStrLn $ "Error: specs directory not found: " ++ specsDir
        else do
            files <- listDirectory specsDir
            let specFiles   = filter (\f -> takeExtension f == ".spec")   files
                fsmFiles    = filter (\f -> takeExtension f == ".fsm")    files
                schemaFiles = filter (\f -> takeExtension f == ".schema") files

            putStrLn "UmbraVox Code Generator v0.1.0"
            putStrLn $ "  Spec files:   " ++ show (length specFiles)
            putStrLn $ "  FSM files:    " ++ show (length fsmFiles)
            putStrLn $ "  Schema files: " ++ show (length schemaFiles)
            putStrLn ""

            -- Process crypto specs
            mapM_ (\f -> do
                putStrLn $ "Processing: " ++ f
                CryptoGen.processSpec (specsDir </> f)
                TestGen.generateCryptoTests (specsDir </> f)
                ) specFiles

            -- Process FSM specs
            mapM_ (\f -> do
                putStrLn $ "Processing: " ++ f
                FSMGen.processFSM (specsDir </> f)
                TestGen.generateFSMTests (specsDir </> f)
                ) fsmFiles

            -- Process CBOR schemas
            mapM_ (\f -> do
                putStrLn $ "Processing: " ++ f
                CBORGen.processSchema (specsDir </> f)
                TestGen.generateCBORTests (specsDir </> f)
                ) schemaFiles

            putStrLn "Code generation complete."
