-- SPDX-License-Identifier: Apache-2.0
-- | App-layer AEAD encryption for at-rest persistence confidentiality.
--
-- This module provides field-level AES-256-GCM encryption for values
-- stored in local databases (Anthony, StateDB, etc.).  It is NOT a
-- replacement for SQLCipher or full-disk encryption — it protects
-- individual sensitive fields so that a raw database dump does not
-- expose plaintext secrets.
--
-- Encrypted fields carry the prefix @UVENC1:@ followed by hex-encoded
-- @nonce(12) || ciphertext || tag(16)@.  'decryptField' rejects any value
-- that does not carry this prefix — all stored fields must be encrypted.
module UmbraVox.Storage.Encryption
    ( StorageKey
    , deriveStorageKey
    , getOrCreateSalt
    , testStorageKey
    , encryptField
    , decryptField
    , isEncryptedField
    ) where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as C8
import Data.List (isPrefixOf)
import Data.Word (Word8)
import System.Directory (createDirectoryIfMissing, doesFileExist)
import System.FilePath (takeDirectory)
import System.IO (withBinaryFile, IOMode(..))
import System.IO.Unsafe (unsafePerformIO)
import System.Posix.Files (setFileMode, ownerReadMode, ownerWriteMode, unionFileModes)

import qualified UmbraVox.Crypto.Generated.FFI.GCM as GCMFFI
import qualified UmbraVox.Crypto.Generated.FFI.HKDF as HKDFFFI
import UmbraVox.Crypto.Random (randomBytes)
import UmbraVox.Crypto.SecureBytes (SecureBytes, fromByteString, toByteString)

------------------------------------------------------------------------
-- Types
------------------------------------------------------------------------

-- | A 32-byte AES-256-GCM key for storage encryption.
--
-- Finding:     M10.2.10 — 'StorageKey' was a plain 'ByteString' type alias,
--              meaning the key material lived on the GC heap with no zeroing
--              on collection and no protection against swap or core dumps.
-- Vulnerability: A plain 'ByteString' key can be paged to swap, included in
--              core dumps, and is never zeroed; an attacker with access to
--              swap or a core file can recover the storage key verbatim.
-- Fix:         Changed 'StorageKey' to a newtype wrapping 'SecureBytes'.
--              'deriveStorageKey' now returns @IO StorageKey@ so the key
--              material is immediately moved into a pinned, mlock'd, zeroed-
--              on-free buffer.  'encryptField' and 'decryptField' extract the
--              key via 'toByteString' only for the duration of the GCM call.
-- Verified:    'deriveStorageKey' wraps the derived bytes in 'fromByteString';
--              callers use 'encryptField' / 'decryptField' rather than
--              extracting the raw key.
newtype StorageKey = StorageKey SecureBytes

-- | Equality comparison for 'StorageKey'.
--
-- Uses 'unsafePerformIO' to extract both keys for byte-by-byte comparison.
-- This is NOT constant-time and must only be used in test assertions or
-- non-security-critical equality checks (e.g. "did I derive the same key
-- twice?").  Never use this as a timing-safe key-equality guard.
instance Eq StorageKey where
    (StorageKey a) == (StorageKey b) =
        unsafePerformIO $ do
            aBS <- toByteString a
            bBS <- toByteString b
            pure (aBS == bBS)

-- | Show instance for 'StorageKey' — prints a fixed placeholder to avoid
-- leaking key material in logs or error messages.
instance Show StorageKey where
    show _ = "<StorageKey>"

------------------------------------------------------------------------
-- Key derivation
------------------------------------------------------------------------

-- Finding: M10.2.9 — deriveStorageKey previously used a hardcoded domain-separator
-- string as the HKDF salt, meaning all installations derived keys from the same
-- PRK base.  If the identity secret were ever compromised or reused across
-- installations the lack of per-install randomness reduces offline brute-force
-- resistance.
--
-- Vulnerability: A fixed salt means every installation with the same identity
-- secret produces the identical storage key.  An attacker with access to one
-- encrypted database and knowledge of the salt (it was in source) could
-- precompute rainbow tables for weak secrets.
--
-- Fix: Accept a caller-supplied 32-byte random salt (loaded or generated by
-- 'getOrCreateSalt') so that every installation's PRK is unique even when the
-- identity secret is identical.
--
-- Verified: 'deriveStorageKey' now requires a per-install random salt; the
-- hardcoded constant no longer participates as the HKDF salt.
--
-- | Derive a 32-byte storage key from an identity secret and a per-install salt.
--
-- Uses HKDF-SHA-256 Extract-then-Expand.  The @salt@ parameter MUST be a
-- 32-byte random value loaded (or freshly generated) by 'getOrCreateSalt'.
-- The info string remains a fixed domain separator.
--
-- Returns an @IO StorageKey@ so the derived key material is immediately moved
-- into a pinned, mlock'd, zeroed-on-free 'SecureBytes' buffer (M10.2.10).
-- The intermediate 'ByteString' values produced by HKDF are short-lived
-- GC-heap allocations; only the final wrapped value is protected.
deriveStorageKey :: ByteString  -- ^ Per-install random salt (32 bytes)
                 -> ByteString  -- ^ Identity secret (IKM)
                 -> IO StorageKey
deriveStorageKey salt secret = do
    !prk   <- HKDFFFI.hkdfSHA256Extract salt secret
    !keyBS <- HKDFFFI.hkdfSHA256Expand prk (C8.pack "UmbraVox_StorageAEAD_v1") 32
    StorageKey <$> fromByteString keyBS

-- Finding: M10.2.9 — No per-install salt file existed; all key derivation used
-- a static compile-time constant.
--
-- Vulnerability: Without a per-install random salt, two installations that share
-- an identity secret (e.g. a backed-up key) produce identical storage keys,
-- giving an attacker with access to both databases a correlation handle and
-- weakening resistance to precomputed attacks.
--
-- Fix: 'getOrCreateSalt' reads a 32-byte random value from
-- @~/.umbravox/storage.salt@, creating it with 'randomBytes 32' on first run.
-- The file is restricted to 0600 permissions so other local users cannot read it.
--
-- Verified: On first run the salt file is created and permissions set to 0600.
-- On subsequent runs the same 32 bytes are returned, giving deterministic key
-- derivation within an installation while remaining unique across installations.
--
-- | Read the per-install 32-byte salt from @~\/.umbravox\/storage.salt@.
--
-- Creates the file (and the @~\/.umbravox\/@ directory) with 'randomBytes 32'
-- if it does not yet exist.  The file is chmod'd 0600 on creation.
getOrCreateSalt :: FilePath -> IO ByteString
getOrCreateSalt saltPath = do
    exists <- doesFileExist saltPath
    if exists
        then withBinaryFile saltPath ReadMode $ \h -> do
            bs <- BS.hGetContents h
            if BS.length bs == 32
                then pure bs
                else do
                    -- Truncated or corrupt salt file — regenerate.
                    salt <- randomBytes 32
                    writeSaltFile saltPath salt
                    pure salt
        else do
            salt <- randomBytes 32
            writeSaltFile saltPath salt
            pure salt
  where
    writeSaltFile path salt = do
        createDirectoryIfMissing True (takeDirectory path)
        withBinaryFile path WriteMode $ \h -> BS.hPut h salt
        setFileMode path (ownerReadMode `unionFileModes` ownerWriteMode)

-- | Deterministic test key.  Non-production use only.
--
-- Uses a fixed all-zero salt and a fixed IKM so test expectations are stable
-- across builds.  Never use in production — the salt provides no real entropy.
--
-- Returns @IO StorageKey@ because 'deriveStorageKey' now wraps the key in
-- a 'SecureBytes' buffer (M10.2.10).
testStorageKey :: IO StorageKey
testStorageKey = deriveStorageKey (BS.replicate 32 0x00) (BS.pack [0..31])

------------------------------------------------------------------------
-- Field encryption / decryption
------------------------------------------------------------------------

-- | Prefix that marks an encrypted field value.
encPrefix :: String
encPrefix = "UVENC1:"

-- | Encrypt a string field for at-rest storage.
--
-- Returns @\"UVENC1:\" ++ hex(nonce || ciphertext || tag)@.
-- Extracts the raw key bytes from the 'SecureBytes' buffer only for the
-- duration of the GCM call (M10.2.10).
encryptField :: StorageKey -> String -> IO String
encryptField (StorageKey keySB) plainStr = do
    nonce <- randomBytes 12
    keyBS <- toByteString keySB
    let !plaintext = C8.pack plainStr
    (ciphertext, tag) <- GCMFFI.gcmEncrypt keyBS nonce BS.empty plaintext
    let !blob = nonce <> ciphertext <> tag
    return (encPrefix ++ C8.unpack (toHex blob))

-- Finding    M10.3.7 — 'decryptField' returned @Just input@ (plaintext
--            passthrough) for any value that lacked the @UVENC1:@ prefix,
--            treating unencrypted stored values as valid decrypted output.
--            This was introduced as a migration shim before v0.1.0 but
--            creates a silent data-integrity hole: a corrupt or injected
--            plaintext record is indistinguishable from a successfully
--            decrypted field.
-- Vulnerability: An attacker (or bug) that writes a raw plaintext value
--            into a storage field will have it silently accepted by callers
--            that rely on 'decryptField' returning 'Nothing' to signal
--            tampered or unencrypted data.  Pre-release code must enforce
--            the invariant that all stored fields are encrypted.
-- Fix:       'decryptField' now returns 'Nothing' for any input that does
--            not carry the @UVENC1:@ prefix.  All stored data must be
--            encrypted; there is no passthrough path.
-- Verified:  'testMigrationSafe' updated to assert 'Nothing' for legacy
--            plaintext; all other tests use 'encryptField' before storage.
--
-- | Decrypt a field value.
--
-- Returns 'Nothing' for any input that does not start with @\"UVENC1:\"@
-- (including legacy plaintext values), and 'Nothing' on malformed
-- ciphertext or GCM authentication failure.  All stored fields must be
-- encrypted — there is no passthrough path.
--
-- Returns @IO (Maybe String)@ because the 'StorageKey' wraps a 'SecureBytes'
-- buffer that must be accessed via 'toByteString' in IO (M10.2.10).
decryptField :: StorageKey -> String -> IO (Maybe String)
decryptField _ input
    | not (isEncryptedField input) = pure Nothing
decryptField (StorageKey keySB) input = do
    keyBS <- toByteString keySB
    let hexPart = drop (length encPrefix) input
    case fromHex (C8.pack hexPart) of
        Nothing  -> pure Nothing
        Just raw -> decryptRaw keyBS raw

-- | Attempt to decrypt a raw blob of @nonce(12) || ciphertext || tag(16)@.
-- Takes a plain 'ByteString' key extracted by the caller from a 'StorageKey'.
decryptRaw :: ByteString -> ByteString -> IO (Maybe String)
decryptRaw key raw
    | BS.length raw < 28 = pure Nothing
    | otherwise = do
        let !nonce      = BS.take 12 raw
            !ctAndTag   = BS.drop 12 raw
            !totalCT    = BS.length ctAndTag
            !ciphertext = BS.take (totalCT - 16) ctAndTag
            !tag        = BS.drop (totalCT - 16) ctAndTag
        mPt <- GCMFFI.gcmDecrypt key nonce BS.empty ciphertext tag
        pure $ case mPt of
            Just pt -> Just (C8.unpack pt)
            Nothing -> Nothing

-- | Check whether a string carries the @UVENC1:@ encrypted-field prefix.
isEncryptedField :: String -> Bool
isEncryptedField s = encPrefix `isPrefixOf` s

------------------------------------------------------------------------
-- Internal — hex encoding helpers
------------------------------------------------------------------------

-- | Encode a 'ByteString' as lowercase hexadecimal.
toHex :: ByteString -> ByteString
toHex = BS.concatMap (\b -> BS.pack [hexNibble (b `div` 16), hexNibble (b `mod` 16)])
  where
    hexNibble :: Word8 -> Word8
    hexNibble n
        | n < 10    = n + 0x30  -- '0'
        | otherwise = n + 0x57  -- 'a' - 10

-- | Decode a hexadecimal 'ByteString'.  Returns 'Nothing' on invalid input.
fromHex :: ByteString -> Maybe ByteString
fromHex bs
    | odd (BS.length bs) = Nothing
    | not (BS.all isHexChar bs) = Nothing
    | otherwise = Just (BS.pack (go (BS.unpack bs)))
  where
    go [] = []
    go (a:b:rest) = (unhex a * 16 + unhex b) : go rest
    go [_] = []
    unhex :: Word8 -> Word8
    unhex w
        | w >= 0x30 && w <= 0x39 = w - 0x30
        | w >= 0x41 && w <= 0x46 = w - 0x37
        | w >= 0x61 && w <= 0x66 = w - 0x57
        | otherwise              = 0
    isHexChar :: Word8 -> Bool
    isHexChar w = (w >= 0x30 && w <= 0x39)
              || (w >= 0x41 && w <= 0x46)
              || (w >= 0x61 && w <= 0x66)
