-- SPDX-License-Identifier: Apache-2.0
-- | App-layer AEAD encryption for at-rest persistence confidentiality.
--
-- This module provides field-level AES-256-GCM encryption for values
-- stored in local databases (Anthony, StateDB, etc.).  It is NOT a
-- replacement for SQLCipher or full-disk encryption — it protects
-- individual sensitive fields so that a raw database dump does not
-- expose plaintext secrets.
--
-- Encrypted fields carry the prefix @UVENC1:@ followed by hex-encoded
-- @nonce(12) || ciphertext || tag(16)@.  Legacy plaintext values pass
-- through 'decryptField' unchanged for migration safety.
module UmbraVox.Storage.Encryption
    ( StorageKey
    , deriveStorageKey
    , getOrCreateSalt
    , testStorageKey
    , encryptField
    , decryptField
    , isEncryptedField
    ) where

import Data.ByteString (ByteString)
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as C8
import Data.List (isPrefixOf)
import Data.Word (Word8)
import System.Directory (createDirectoryIfMissing, doesFileExist)
import System.FilePath (takeDirectory)
import System.IO (withBinaryFile, IOMode(..))
import System.Posix.Files (setFileMode, ownerReadMode, ownerWriteMode, unionFileModes)

import UmbraVox.Crypto.GCM (gcmEncrypt, gcmDecrypt)
import UmbraVox.Crypto.HKDF (hkdfSHA256Extract, hkdfSHA256Expand)
import UmbraVox.Crypto.Random (randomBytes)

------------------------------------------------------------------------
-- Types
------------------------------------------------------------------------

-- | A 32-byte AES-256-GCM key for storage encryption.
type StorageKey = ByteString

------------------------------------------------------------------------
-- Key derivation
------------------------------------------------------------------------

-- Finding: M10.2.9 — deriveStorageKey previously used a hardcoded domain-separator
-- string as the HKDF salt, meaning all installations derived keys from the same
-- PRK base.  If the identity secret were ever compromised or reused across
-- installations the lack of per-install randomness reduces offline brute-force
-- resistance.
--
-- Vulnerability: A fixed salt means every installation with the same identity
-- secret produces the identical storage key.  An attacker with access to one
-- encrypted database and knowledge of the salt (it was in source) could
-- precompute rainbow tables for weak secrets.
--
-- Fix: Accept a caller-supplied 32-byte random salt (loaded or generated by
-- 'getOrCreateSalt') so that every installation's PRK is unique even when the
-- identity secret is identical.
--
-- Verified: 'deriveStorageKey' now requires a per-install random salt; the
-- hardcoded constant no longer participates as the HKDF salt.
--
-- | Derive a 32-byte storage key from an identity secret and a per-install salt.
--
-- Uses HKDF-SHA-256 Extract-then-Expand.  The @salt@ parameter MUST be a
-- 32-byte random value loaded (or freshly generated) by 'getOrCreateSalt'.
-- The info string remains a fixed domain separator.
--
-- NOTE: Key zeroing is not performed because Haskell ByteStrings are
-- immutable and GC-managed.  True key zeroing requires FFI to
-- memset_s / explicit_bzero; this is tracked as a known limitation.
deriveStorageKey :: ByteString  -- ^ Per-install random salt (32 bytes)
                 -> ByteString  -- ^ Identity secret (IKM)
                 -> StorageKey
deriveStorageKey salt secret =
    let !prk = hkdfSHA256Extract salt secret
    in hkdfSHA256Expand prk (C8.pack "UmbraVox_StorageAEAD_v1") 32

-- Finding: M10.2.9 — No per-install salt file existed; all key derivation used
-- a static compile-time constant.
--
-- Vulnerability: Without a per-install random salt, two installations that share
-- an identity secret (e.g. a backed-up key) produce identical storage keys,
-- giving an attacker with access to both databases a correlation handle and
-- weakening resistance to precomputed attacks.
--
-- Fix: 'getOrCreateSalt' reads a 32-byte random value from
-- @~/.umbravox/storage.salt@, creating it with 'randomBytes 32' on first run.
-- The file is restricted to 0600 permissions so other local users cannot read it.
--
-- Verified: On first run the salt file is created and permissions set to 0600.
-- On subsequent runs the same 32 bytes are returned, giving deterministic key
-- derivation within an installation while remaining unique across installations.
--
-- | Read the per-install 32-byte salt from @~\/.umbravox\/storage.salt@.
--
-- Creates the file (and the @~\/.umbravox\/@ directory) with 'randomBytes 32'
-- if it does not yet exist.  The file is chmod'd 0600 on creation.
getOrCreateSalt :: FilePath -> IO ByteString
getOrCreateSalt saltPath = do
    exists <- doesFileExist saltPath
    if exists
        then withBinaryFile saltPath ReadMode $ \h -> do
            bs <- BS.hGetContents h
            if BS.length bs == 32
                then pure bs
                else do
                    -- Truncated or corrupt salt file — regenerate.
                    salt <- randomBytes 32
                    writeSaltFile saltPath salt
                    pure salt
        else do
            salt <- randomBytes 32
            writeSaltFile saltPath salt
            pure salt
  where
    writeSaltFile path salt = do
        createDirectoryIfMissing True (takeDirectory path)
        withBinaryFile path WriteMode $ \h -> BS.hPut h salt
        setFileMode path (ownerReadMode `unionFileModes` ownerWriteMode)

-- | Deterministic test key.  Non-production use only.
--
-- Uses a fixed all-zero salt and a fixed IKM so test expectations are stable
-- across builds.  Never use in production — the salt provides no real entropy.
testStorageKey :: StorageKey
testStorageKey = deriveStorageKey (BS.replicate 32 0x00) (BS.pack [0..31])

------------------------------------------------------------------------
-- Field encryption / decryption
------------------------------------------------------------------------

-- | Prefix that marks an encrypted field value.
encPrefix :: String
encPrefix = "UVENC1:"

-- | Encrypt a string field for at-rest storage.
--
-- Returns @\"UVENC1:\" ++ hex(nonce || ciphertext || tag)@.
encryptField :: StorageKey -> String -> IO String
encryptField key plainStr = do
    nonce <- randomBytes 12
    let !plaintext      = C8.pack plainStr
        !(ciphertext, tag) = gcmEncrypt key nonce BS.empty plaintext
        !blob           = nonce <> ciphertext <> tag
    return (encPrefix ++ C8.unpack (toHex blob))

-- | Decrypt a field value.
--
-- * If the input does not start with @\"UVENC1:\"@, it is returned
--   unchanged ('Just') for migration-safe passthrough of legacy
--   plaintext.
-- * Returns 'Nothing' on malformed ciphertext or authentication
--   failure.
decryptField :: StorageKey -> String -> Maybe String
decryptField key input
    | not (isEncryptedField input) = Just input
    | otherwise =
        let hexPart = drop (length encPrefix) input
        in case fromHex (C8.pack hexPart) of
            Nothing  -> Nothing
            Just raw -> decryptRaw key raw

-- | Attempt to decrypt a raw blob of @nonce(12) || ciphertext || tag(16)@.
decryptRaw :: StorageKey -> ByteString -> Maybe String
decryptRaw key raw
    | BS.length raw < 28 = Nothing
    | otherwise =
        let !nonce      = BS.take 12 raw
            !ctAndTag   = BS.drop 12 raw
            !totalCT    = BS.length ctAndTag
            !ciphertext = BS.take (totalCT - 16) ctAndTag
            !tag        = BS.drop (totalCT - 16) ctAndTag
        in case gcmDecrypt key nonce BS.empty ciphertext tag of
            Just pt -> Just (C8.unpack pt)
            Nothing -> Nothing

-- | Check whether a string carries the @UVENC1:@ encrypted-field prefix.
isEncryptedField :: String -> Bool
isEncryptedField s = encPrefix `isPrefixOf` s

------------------------------------------------------------------------
-- Internal — hex encoding helpers
------------------------------------------------------------------------

-- | Encode a 'ByteString' as lowercase hexadecimal.
toHex :: ByteString -> ByteString
toHex = BS.concatMap (\b -> BS.pack [hexNibble (b `div` 16), hexNibble (b `mod` 16)])
  where
    hexNibble :: Word8 -> Word8
    hexNibble n
        | n < 10    = n + 0x30  -- '0'
        | otherwise = n + 0x57  -- 'a' - 10

-- | Decode a hexadecimal 'ByteString'.  Returns 'Nothing' on invalid input.
fromHex :: ByteString -> Maybe ByteString
fromHex bs
    | odd (BS.length bs) = Nothing
    | not (BS.all isHexChar bs) = Nothing
    | otherwise = Just (BS.pack (go (BS.unpack bs)))
  where
    go [] = []
    go (a:b:rest) = (unhex a * 16 + unhex b) : go rest
    go [_] = []
    unhex :: Word8 -> Word8
    unhex w
        | w >= 0x30 && w <= 0x39 = w - 0x30
        | w >= 0x41 && w <= 0x46 = w - 0x37
        | w >= 0x61 && w <= 0x66 = w - 0x57
        | otherwise              = 0
    isHexChar :: Word8 -> Bool
    isHexChar w = (w >= 0x30 && w <= 0x39)
              || (w >= 0x41 && w <= 0x46)
              || (w >= 0x61 && w <= 0x66)
