{-# LANGUAGE OverloadedStrings #-}
-- | Protocol-level differential testing against libsignal traces.
--
-- This module will consume protocol traces generated by the libsignal
-- oracle VM (nix/vm-libsignal-protocol-oracle.nix) and compare
-- UmbraVOX's X3DH/PQXDH/DoubleRatchet behavior against them.
--
-- Current status: SCAFFOLD — the libsignal oracle VM is not yet built.
-- When traces are available at build/differential/traces/, this module
-- will load them and run semantic comparisons.
--
-- Known divergences are documented in:
-- test/evidence/formal-proofs/audit/protocol_divergences.md
module Test.Crypto.Differential.ProtocolLibsignal
    ( protocolLibsignalTests
    ) where

import qualified Data.ByteString as BS
import System.Directory (doesDirectoryExist)

-- | Run protocol differential tests against libsignal traces.
-- Returns True if all pass or if no traces are available (SKIP).
protocolLibsignalTests :: IO Bool
protocolLibsignalTests = do
    putStrLn "[ProtocolLibsignal] Checking for libsignal traces..."
    let tracesDir = "build/differential/traces"
    exists <- doesDirectoryExist tracesDir
    if exists then do
        putStrLn "  Found traces directory — running protocol comparisons..."
        -- TODO: Load JSON traces, replay protocol steps, compare state
        putStrLn "  SKIP: trace consumer not yet implemented"
        putStrLn "[ProtocolLibsignal] 0/0 suites (traces not yet available)"
        return True
    else do
        putStrLn "  No traces directory found (build/differential/traces/)"
        putStrLn "  Run 'make differential-protocol-vectors' to generate traces"
        putStrLn "[ProtocolLibsignal] SKIP (oracle VM not built)"
        return True
