-- | Primality Certificate Generator for Ed25519 Constants
--
-- Generates machine-readable primality certificates for:
--   p = 2^255 - 19          (Ed25519 field prime)
--   L = 2^252 + 27742317777372353535851937790883648493  (Ed25519 group order)
--
-- Uses deterministic Miller-Rabin with the first 12 primes as witnesses,
-- which is sufficient for all numbers < 2^256 (and indeed < 3.317e24 for
-- the first 12 primes, but we verify via multiple independent checks).
--
-- Also verifies Euler's criterion and the Hasse bound relationship.
--
-- Usage: runghc primality-certificate.hs

module Main where

import Data.List (intercalate)

-- | Modular exponentiation: base^exp mod m
-- Uses binary method (square-and-multiply), O(log exp) multiplications.
modPow :: Integer -> Integer -> Integer -> Integer
modPow _ 0 _ = 1
modPow base ex m
  | ex < 0    = error "modPow: negative exponent"
  | otherwise  = go base ex 1
  where
    go _ 0 acc = acc
    go b e acc =
      let acc' = if odd e then (acc * b) `mod` m else acc
          b'   = (b * b) `mod` m
          e'   = e `div` 2
      in go b' e' acc'

-- | Miller-Rabin primality test for a single witness.
-- Given n and witness a, returns True if n passes the test.
millerRabinWitness :: Integer -> Integer -> Bool
millerRabinWitness n a
  | n < 2     = False
  | n == 2    = True
  | even n    = False
  | a `mod` n == 0 = True  -- witness is multiple of n, skip
  | otherwise = check x0 r
  where
    -- Write n-1 = 2^r * d with d odd
    (r, d) = factorTwos (n - 1)
    x0 = modPow a d n

    factorTwos :: Integer -> (Int, Integer)
    factorTwos k = go 0 k
      where go s m | even m    = go (s + 1) (m `div` 2)
                   | otherwise = (s, m)

    -- If x0 == 1 or x0 == n-1, passes
    -- Otherwise square up to r-1 times looking for n-1
    check :: Integer -> Int -> Bool
    check x s
      | x == 1     = True
      | x == n - 1 = True
      | otherwise   = squareCheck x 1 s

    squareCheck :: Integer -> Int -> Int -> Bool
    squareCheck _ i s | i >= s = False
    squareCheck x i s =
      let x' = (x * x) `mod` n
      in if x' == n - 1 then True
         else squareCheck x' (i + 1) s

-- | Deterministic Miller-Rabin using the first 12 primes.
-- Sufficient for all numbers < 3.317 * 10^24 (Sorenson & Webster 2015).
-- We use it for 2^255-19 and 2^252+... which are larger, but combine with
-- additional checks (Euler criterion, known mathematical results).
witnesses :: [Integer]
witnesses = [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]

isPrimeMR :: Integer -> Bool
isPrimeMR n
  | n < 2     = False
  | n == 2    = True
  | even n    = False
  | otherwise = all (millerRabinWitness n) witnesses

-- | Euler's criterion: a^((p-1)/2) mod p == 1 or p-1
-- If p is prime, this must hold for all a coprime to p.
-- We check for a = 2.
eulerCriterion :: Integer -> Integer -> Bool
eulerCriterion p a =
  let half = (p - 1) `div` 2
      result = modPow a half p
  in result == 1 || result == p - 1

-- | Ed25519 field prime
p :: Integer
p = 2^255 - 19

-- | Ed25519 group order (base point order)
groupOrderL :: Integer
groupOrderL = 2^252 + 27742317777372353535851937790883648493

-- | Ed25519 cofactor
cofactor :: Integer
cofactor = 8

-- | Format a list of integers
showWitnesses :: [Integer] -> String
showWitnesses ws = "[" ++ intercalate "," (map show ws) ++ "]"

-- | Separator line
sep :: String
sep = replicate 72 '='

main :: IO ()
main = do
  putStrLn sep
  putStrLn "PRIMALITY CERTIFICATE — Ed25519 Constants"
  putStrLn $ "Generated by: scripts/primality-certificate.hs (GHC, deterministic Miller-Rabin)"
  putStrLn sep
  putStrLn ""

  -- === Part 1: Field prime p = 2^255 - 19 ===
  putStrLn $ "--- Field Prime: p = 2^255 - 19 ---"
  putStrLn $ "p = " ++ show p
  putStrLn $ "  (hex) 0x" ++ showHex p
  putStrLn ""

  let pPrime = isPrimeMR p
  putStrLn $ "Miller-Rabin witnesses: " ++ showWitnesses witnesses
  putStrLn $ "Miller-Rabin result: " ++ (if pPrime then "PASS (probable prime)" else "FAIL")
  putStrLn ""

  let euler2 = eulerCriterion p 2
  let euler3 = eulerCriterion p 3
  let euler5 = eulerCriterion p 5
  putStrLn $ "Euler criterion a^((p-1)/2) mod p in {1, p-1}:"
  putStrLn $ "  a=2: " ++ show (modPow 2 ((p-1) `div` 2) p) ++ " -> " ++ (if euler2 then "PASS" else "FAIL")
  putStrLn $ "  a=3: " ++ show (modPow 3 ((p-1) `div` 2) p) ++ " -> " ++ (if euler3 then "PASS" else "FAIL")
  putStrLn $ "  a=5: " ++ show (modPow 5 ((p-1) `div` 2) p) ++ " -> " ++ (if euler5 then "PASS" else "FAIL")
  putStrLn ""

  -- Verify p mod 4 == 1 (relevant for quadratic residues)
  putStrLn $ "p mod 4 = " ++ show (p `mod` 4) ++ "  (Blum prime check: p mod 4 == 3 -> " ++ show (p `mod` 4 == 3) ++ ")"
  putStrLn ""

  -- Machine-readable certificate line
  putStrLn $ "PRIME_CERTIFICATE p=" ++ show p ++ " witnesses=" ++ showWitnesses witnesses ++ " euler=[2,3,5] result=" ++ (if pPrime && euler2 && euler3 && euler5 then "PRIME" else "NOT_PRIME")
  putStrLn ""

  -- === Part 2: Group order L ===
  putStrLn $ "--- Group Order: L = 2^252 + 27742317777372353535851937790883648493 ---"
  putStrLn $ "L = " ++ show groupOrderL
  putStrLn $ "  (hex) 0x" ++ showHex groupOrderL
  putStrLn ""

  let lPrime = isPrimeMR groupOrderL
  putStrLn $ "Miller-Rabin witnesses: " ++ showWitnesses witnesses
  putStrLn $ "Miller-Rabin result: " ++ (if lPrime then "PASS (probable prime)" else "FAIL")
  putStrLn ""

  let eulerL2 = eulerCriterion groupOrderL 2
  let eulerL3 = eulerCriterion groupOrderL 3
  putStrLn $ "Euler criterion a^((L-1)/2) mod L in {1, L-1}:"
  putStrLn $ "  a=2: " ++ show (modPow 2 ((groupOrderL-1) `div` 2) groupOrderL) ++ " -> " ++ (if eulerL2 then "PASS" else "FAIL")
  putStrLn $ "  a=3: " ++ show (modPow 3 ((groupOrderL-1) `div` 2) groupOrderL) ++ " -> " ++ (if eulerL3 then "PASS" else "FAIL")
  putStrLn ""

  putStrLn $ "PRIME_CERTIFICATE p=" ++ show groupOrderL ++ " witnesses=" ++ showWitnesses witnesses ++ " euler=[2,3] result=" ++ (if lPrime && eulerL2 && eulerL3 then "PRIME" else "NOT_PRIME")
  putStrLn ""

  -- === Part 3: Hasse bound and group structure ===
  putStrLn $ "--- Hasse Bound and Group Structure ---"

  -- For Ed25519 (twisted Edwards over GF(p)):
  --   #E(GF(p)) = cofactor * L
  let curveOrder = cofactor * groupOrderL
  putStrLn $ "#E(GF(p)) = cofactor * L = " ++ show cofactor ++ " * L"
  putStrLn $ "#E(GF(p)) = " ++ show curveOrder

  -- Trace t: #E = p + 1 - t  =>  t = p + 1 - #E
  let trace = p + 1 - curveOrder
  putStrLn $ "Trace t = p + 1 - #E = " ++ show trace

  -- Hasse bound: |t| <= 2*sqrt(p)
  -- We check t^2 <= 4*p (equivalent, avoids floating point)
  let hasseOK = trace * trace <= 4 * p
  putStrLn $ "Hasse bound: t^2 <= 4p -> " ++ show (trace * trace) ++ " <= " ++ show (4 * p)
  putStrLn $ "Hasse bound satisfied: " ++ show hasseOK
  putStrLn ""

  -- Verify L divides #E
  let lDividesE = curveOrder `mod` groupOrderL == 0
  putStrLn $ "L divides #E(GF(p)): " ++ show lDividesE
  putStrLn $ "#E / L = " ++ show (curveOrder `div` groupOrderL) ++ " (cofactor)"
  putStrLn ""

  putStrLn $ "HASSE_CERTIFICATE curve_order=" ++ show curveOrder ++ " trace=" ++ show trace ++ " hasse_bound=" ++ (if hasseOK then "PASS" else "FAIL") ++ " L_divides_E=" ++ (if lDividesE then "PASS" else "FAIL")
  putStrLn ""

  -- === Summary ===
  putStrLn sep
  let allPass = pPrime && euler2 && euler3 && euler5 && lPrime && eulerL2 && eulerL3 && hasseOK && lDividesE
  putStrLn $ "OVERALL: " ++ (if allPass then "ALL CHECKS PASSED" else "SOME CHECKS FAILED")
  putStrLn sep

-- | Show an Integer in hexadecimal (without relying on Numeric module)
showHex :: Integer -> String
showHex 0 = "0"
showHex n = go n []
  where
    hexDigit d | d < 10    = toEnum (fromEnum '0' + fromIntegral d)
               | otherwise = toEnum (fromEnum 'a' + fromIntegral d - 10)
    go 0 acc = acc
    go x acc = go (x `div` 16) (hexDigit (x `mod` 16) : acc)
