// Command vm-init is the in-guest initialization binary for UmbraVOX
// development VMs.
//
// This is the Go replacement for the shell-based .vm-init.sh script
// generated by generateInitScript in cmd_exec.go. It handles all guest
// setup: mounting disks, copying source, linking caches, configuring
// environment variables, and dispatching to exec or interactive mode.
//
// Usage (called from the minimal .vm-init.sh wrapper):
//
//	vm-init exec          Run .vm-exec-cmd and write exit status
//	vm-init interactive   Show banner and drop to bash --login
//	vm-init gui           Write profile script for VGA login
//
// Cross-compiled for linux/amd64 and placed on the source disk at
// tools/bin/vm-init by the host orchestrator.
package main

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"syscall"
)

const (
	srcMount  = "/mnt/src"
	outputDir = "/output"
	cacheDir  = "/cache"
	workDir   = "/work/umbravox"

	srcDevice   = "/dev/vdb"
	cacheDevice = "/dev/vdc"
)

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "Usage: vm-init <exec|interactive|gui>")
		os.Exit(2)
	}
	mode := os.Args[1]

	setupEnvironment()
	setupCabalConfig()
	mountSource()
	mountOutput()
	mountCache()
	copySourceToWorkspace()
	linkBuildCache()

	if err := os.Chdir(workDir); err != nil {
		fmt.Fprintf(os.Stderr, "vm-init: chdir %s: %v\n", workDir, err)
		os.Exit(1)
	}

	setProjectEnv()
	discoverFStarHome()
	discoverCoqPath()

	switch mode {
	case "exec":
		os.Exit(runExec())
	case "interactive":
		showBanner()
		execBash()
	case "gui":
		showBanner()
		writeGUIProfile()
		fmt.Println("  GUI mode: log in on the VGA console (root, no password).")
		fmt.Println()
	default:
		fmt.Fprintf(os.Stderr, "vm-init: unknown mode %q\n", mode)
		os.Exit(2)
	}
}

// setupEnvironment sets the baseline PATH, HOME, and pkg-config paths.
func setupEnvironment() {
	os.Setenv("HOME", "/root")
	os.Setenv("PATH", "/run/current-system/sw/bin:/run/current-system/sw/sbin:"+os.Getenv("PATH"))
	// NixOS puts .pc files under the system profile; cabal's pkgconfig-depends
	// needs PKG_CONFIG_PATH set so pkg-config can locate them (e.g. sqlite3.pc).
	setPkgConfigPath()
}

// setPkgConfigPath discovers NixOS pkg-config directories under the system
// profile and sets PKG_CONFIG_PATH so cabal/pkg-config can find .pc files.
func setPkgConfigPath() {
	var dirs []string
	candidates := []string{
		"/run/current-system/sw/lib/pkgconfig",
		"/run/current-system/sw/share/pkgconfig",
	}
	for _, d := range candidates {
		if fi, err := os.Stat(d); err == nil && fi.IsDir() {
			dirs = append(dirs, d)
		}
	}
	if existing := os.Getenv("PKG_CONFIG_PATH"); existing != "" {
		dirs = append(dirs, existing)
	}
	if len(dirs) > 0 {
		os.Setenv("PKG_CONFIG_PATH", strings.Join(dirs, ":"))
	}
}

// setupCabalConfig writes an offline cabal configuration.
func setupCabalConfig() {
	dir := "/root/.cabal"
	os.MkdirAll(dir, 0o755)
	os.WriteFile(filepath.Join(dir, "config"), []byte("offline: True\nnix: False\n"), 0o644)
}

// mountSource mounts the read-only source disk at /mnt/src.
func mountSource() {
	os.MkdirAll(srcMount, 0o755)
	if isMountpoint(srcMount) {
		return
	}
	run("mount", "-o", "ro", srcDevice, srcMount)
}

// mountOutput mounts the 9p output share at /output.
func mountOutput() {
	os.MkdirAll(outputDir, 0o755)
	run("mount", "-t", "9p", "-o", "trans=virtio,version=9p2000.L", "output", outputDir)
}

// mountCache mounts the persistent build cache disk, formatting it if needed.
func mountCache() {
	os.MkdirAll(cacheDir, 0o755)
	if !blockDeviceExists(cacheDevice) {
		return
	}
	// Format if no filesystem signature is found.
	if err := exec.Command("blkid", cacheDevice).Run(); err != nil {
		run("mkfs.ext4", "-q", cacheDevice)
	}
	run("mount", cacheDevice, cacheDir)
	os.MkdirAll(filepath.Join(cacheDir, "dist-newstyle"), 0o755)
	os.MkdirAll(filepath.Join(cacheDir, ".cabal-store"), 0o755)
}

// copySourceToWorkspace copies the source tree to a writable location.
func copySourceToWorkspace() {
	readyFile := filepath.Join(workDir, ".vm-source-ready")
	if _, err := os.Stat(readyFile); err == nil {
		return // already copied
	}
	os.MkdirAll(workDir, 0o755)
	// Use cp -a for faithful copy including symlinks and permissions,
	// matching the original shell script behavior.
	exec.Command("cp", "-a", srcMount+"/.", workDir+"/").Run()
	os.WriteFile(readyFile, nil, 0o644)
}

// linkBuildCache symlinks dist-newstyle and cabal store into the cache disk.
func linkBuildCache() {
	if fi, err := os.Stat(filepath.Join(cacheDir, "dist-newstyle")); err == nil && fi.IsDir() {
		os.RemoveAll(filepath.Join(workDir, "dist-newstyle"))
		os.Symlink(filepath.Join(cacheDir, "dist-newstyle"), filepath.Join(workDir, "dist-newstyle"))
	}
	if fi, err := os.Stat(filepath.Join(cacheDir, ".cabal-store")); err == nil && fi.IsDir() {
		os.MkdirAll("/root/.cabal", 0o755)
		os.Remove("/root/.cabal/store")
		os.Symlink(filepath.Join(cacheDir, ".cabal-store"), "/root/.cabal/store")
	}
}

// setProjectEnv sets UmbraVOX-specific environment variables.
func setProjectEnv() {
	os.Setenv("UMBRAVOX_ROOT", workDir)
	os.Setenv("UMBRAVOX_VM", "1")
	os.Setenv("PATH", filepath.Join(workDir, "scripts")+":"+os.Getenv("PATH"))
	os.Unsetenv("LD_LIBRARY_PATH")
}

// discoverFStarHome locates F* and sets FSTAR_HOME.
func discoverFStarHome() {
	exePath, err := exec.LookPath("fstar.exe")
	if err != nil {
		return
	}
	real, err := filepath.EvalSymlinks(exePath)
	if err != nil {
		return
	}
	os.Setenv("FSTAR_HOME", filepath.Dir(filepath.Dir(real)))
}

// discoverCoqPath scans for Coq user-contrib directories.
func discoverCoqPath() {
	base := "/run/current-system/sw/lib/coq"
	entries, err := os.ReadDir(base)
	if err != nil {
		return
	}
	var dirs []string
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		uc := filepath.Join(base, e.Name(), "user-contrib")
		if fi, err := os.Stat(uc); err == nil && fi.IsDir() {
			dirs = append(dirs, uc)
		}
	}
	if len(dirs) > 0 {
		os.Setenv("COQPATH", strings.Join(dirs, ":"))
	}
}

// runExec reads the command from .vm-exec-cmd, executes it, writes the
// exit status to the output share, and powers off the VM.
func runExec() int {
	cmdBytes, err := os.ReadFile(filepath.Join(srcMount, ".vm-exec-cmd"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "vm-init: cannot read .vm-exec-cmd: %v\n", err)
		return 1
	}
	cmdStr := strings.TrimSpace(string(cmdBytes))

	fmt.Println()
	fmt.Println("========================================")
	fmt.Printf("  UmbraVOX VM: %s\n", cmdStr)
	fmt.Println("========================================")
	fmt.Println()

	// eval is intentional: the command originates from the host CLI (not guest
	// input) and may contain shell features like pipes and redirects. The VM
	// is sandboxed by QEMU with no network access, so this does not expand
	// the trust boundary.
	cmd := exec.Command("/bin/bash", "-c", cmdStr)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = os.Environ()

	status := 0
	if err := cmd.Run(); err != nil {
		if exitErr, ok := err.(*exec.ExitError); ok {
			status = exitErr.ExitCode()
		} else {
			status = 1
		}
	}

	// Write exit status to output share.
	statusStr := fmt.Sprintf("%d\n", status)
	if err := os.WriteFile(filepath.Join(outputDir, "vm-exec-status"), []byte(statusStr), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "vm-init: failed to write vm-exec-status: %v\n", err)
	}
	exec.Command("sync").Run()

	fmt.Println()
	if status == 0 {
		fmt.Println("VM_RESULT=PASS")
	} else {
		fmt.Printf("VM_RESULT=FAIL (exit %d)\n", status)
	}

	exec.Command("systemctl", "poweroff").Run()
	return status
}

// showBanner prints the UmbraVOX dev shell banner.
func showBanner() {
	ghcVer := cmdOutput("ghc", "--numeric-version")
	cabalVer := cmdOutput("cabal", "--numeric-version")
	fstarVer := cmdOutput("fstar.exe", "--version")
	if idx := strings.Index(fstarVer, "\n"); idx >= 0 {
		fstarVer = fstarVer[:idx]
	}
	fstarVer = strings.TrimPrefix(fstarVer, "F* ")
	z3Ver := strings.TrimPrefix(cmdOutput("z3", "--version"), "Z3 version ")

	kernel := cmdOutput("uname", "-r")

	fmt.Println()
	fmt.Println("\033[35m  \u2566 \u2566\u2554\u2566\u2557\u2554\u2557 \u2566\u2550\u2557\u2554\u2550\u2557\u2566  \u2566\u2554\u2550\u2557\u2550\u2557 \u2566\033[0m")
	fmt.Println("\033[35m  \u2551 \u2551\u2551\u2551\u2551\u2560\u2569\u2557\u2560\u2566\u2557\u2560\u2550\u2563\u255a\u2557\u2554\u255d\u2551 \u2551\u2554\u2569\u2566\u255d\033[0m")
	fmt.Println("\033[35m  \u255a\u2550\u255d\u2569 \u2569\u255a\u2550\u255d\u2569\u255a\u2550\u2569 \u2569 \u255a\u255d \u255a\u2550\u255d\u2569 \u255a\u2550\033[0m")
	fmt.Println("\033[33m  Post-Quantum Encrypted Messaging\033[0m")
	fmt.Println()
	fmt.Println("  \033[1;32m[ VM DEVELOPMENT SHELL ]\033[0m  \033[90m(NixOS QEMU Guest)\033[0m")
	fmt.Println()
	fmt.Printf("  Source: %s\n", workDir)
	fmt.Printf("  Kernel: %s\n", kernel)
	fmt.Printf("  GHC:    %s\n", ghcVer)
	fmt.Printf("  Cabal:  %s\n", cabalVer)
	fmt.Printf("  F*:     %s\n", fstarVer)
	fmt.Printf("  Z3:     %s\n", z3Ver)
	fmt.Println()
	fmt.Println("  Commands:")
	fmt.Println("    cabal build all                Build everything")
	fmt.Println("    cabal test umbravox-test       Run tests")
	fmt.Println("    exit / Ctrl-D                  Shut down VM")
	fmt.Println()
}

// execBash replaces the current process with bash --login.
func execBash() {
	bashPath, err := exec.LookPath("bash")
	if err != nil {
		bashPath = "/bin/bash"
	}
	syscall.Exec(bashPath, []string{"bash", "--login"}, os.Environ())
}

// writeGUIProfile writes a login profile for GUI/VGA console mode.
// If .vm-exec-cmd exists on the source disk, the command is appended
// to the profile so it auto-runs on VGA login (used by ./uv run gui).
func writeGUIProfile() {
	os.MkdirAll("/etc/profile.d", 0o755)
	profile := `export HOME=/root
export UMBRAVOX_ROOT=/work/umbravox
export PATH="/work/umbravox/scripts:/run/current-system/sw/bin:/run/current-system/sw/sbin:$PATH"
unset LD_LIBRARY_PATH 2>/dev/null || true
cd /work/umbravox 2>/dev/null || true
`
	// Auto-run command if provided (./uv run gui injects .vm-exec-cmd)
	if cmdBytes, err := os.ReadFile(filepath.Join(srcMount, ".vm-exec-cmd")); err == nil {
		cmd := strings.TrimSpace(string(cmdBytes))
		if cmd != "" {
			profile += fmt.Sprintf("\n# Auto-run from ./uv run gui\n%s\n# Shut down VM when app exits\nsystemctl poweroff\n", cmd)
		}
	}
	os.WriteFile("/etc/profile.d/umbravox-dev.sh", []byte(profile), 0o644)
}

// --- helpers ---

// run executes a command, ignoring errors (matches shell || true pattern).
func run(name string, args ...string) {
	exec.Command(name, args...).Run()
}

// cmdOutput runs a command and returns its trimmed stdout, or "N/A".
func cmdOutput(name string, args ...string) string {
	out, err := exec.Command(name, args...).Output()
	if err != nil {
		return "N/A"
	}
	return strings.TrimSpace(string(out))
}

// isMountpoint checks if a path is already a mount point.
func isMountpoint(path string) bool {
	return exec.Command("mountpoint", "-q", path).Run() == nil
}

// blockDeviceExists checks if a block device exists.
func blockDeviceExists(path string) bool {
	fi, err := os.Stat(path)
	if err != nil {
		return false
	}
	return fi.Mode()&os.ModeDevice != 0
}
