-- SPDX-License-Identifier: Apache-2.0
-- | Build version information derived from git.
--
-- This module is regenerated by @scripts/gen-version.sh@ before each build.
-- If the script hasn't run, fallback values are used.
module UmbraVox.Version
    ( version
    , versionFull
    , versionShort
    ) where

import System.IO.Unsafe (unsafePerformIO)
import System.Process (readProcess)
import Control.Exception (SomeException, catch)

-- | Full version string, e.g. "v0.0.2" or "v0.0.2-dirty-6d6cf4b"
version :: String
version = unsafePerformIO getVersion
{-# NOINLINE version #-}

-- | Full version with app name, e.g. "UmbraVOX v0.0.2"
versionFull :: String
versionFull = "UmbraVOX " ++ version

-- | Short version for status bar, e.g. "v0.0.2"
versionShort :: String
versionShort = version

-- | Query git for the current version at startup.
-- Uses git describe --tags --dirty to get tag + dirty state.
getVersion :: IO String
getVersion = do
    desc <- readProcess "git" ["describe", "--tags", "--always", "--dirty"] ""
             `catch` (\(_ :: SomeException) -> pure "v0.0.0-unknown")
    let trimmed = filter (\c -> c /= '\n' && c /= '\r' && c /= ' ') desc
    pure $ if null trimmed then "v0.0.0-unknown" else trimmed
